### ISSUE TITLE
Zeitwerk does not automatically pick up gems, provided in vendor directory

### ISSUE THREAD

**Issue by nhh** [fxn/zeitwerk#101]
Whats the actual correct way of autoloading external dependecies?

Initializing zeitwerk via `loader = Zeitwerk::Loader.for_gem` does not pick up any 3rd party deps like "Sinatra".

Is this intended? If so, can you point me to a more "solid" implementation for a loading pattern like this:
```ruby
Dir.glob('vendor/ruby/**/gems/**/lib/').each { |gem| loader.push_dir(gem) }
```

Is there a way to integrate with bundler and its installed dependencies?

**Comment by fxn** [comment]
You cannot do that.

Each individual gem decides how is their code loaded.

For those using Zeitwerk themselves, you will be able to autoload and eager loaded. That should normally be mentioned in their documentation. The rest, you need to issue `require` calls for their code, as usual. Those ones can have arbitrary project structures and load their code however they want.

**Comment by nhh** [comment]
Oh really! 🧐 Thats interesting. I guess automatically providing all dependencies would be out of scope and a bit too much if the good. Thanks for the info!

**Comment by fxn** [comment]
It cannot be done, Zeitwerk cannot manage arbitrary Ruby projects, that is why projects have constraints, there is an inflector, etc.

Zeitwerk is a code loader for _your_ project, not 3rd party.

**Comment by nhh** [comment]
Yep 😋 i misunderstood about that.
