### ISSUE TITLE
Zeitwerk silently breaks if there's an error in a parent class

### ISSUE THREAD

**Issue by swistak** [fxn/zeitwerk#102]
Exmple:

```
class ApiBase < ActionController::API
  include ActionController::Serialization # <- this fails because the gem thatprovides this is missing

  def foo
    puts "foo"
  end
end

class ItemsController < ApiBase
  def bar
    foo
  end
end
```

Result:

Everything loads fine except:

ItemsController#bar results in:

`NoMethodError - undefined method `foo' for #<ItemsController:0x00007ff95c432828>`

Class simply stops loading, when exception is thrown, but then class is "created" anyway but without any method bellow the error.

**Comment by fxn** [comment]
Several comments.

Zeitwerk does not shallow errors. For example, take this example:

```
% cat lib/foo.rb
class Foo < Bar
end
% cat lib/bar.rb
class Bar
  1/0
end
% cat test.rb
require "zeitwerk"

loader = Zeitwerk::Loader.new
loader.push_dir("lib")
loader.setup

Foo
```

If you run that code, you'll get `divided by 0 (ZeroDivisionError)`.

Now, if application code rescues the exception, then class `Bar` gets partially defined. But Zeitwerk does nothing special in that regard, that is how Ruby works. If an exception is raised in the middle of a class or module definition, you got defined only what ran up to that spot, the rest was not executed.

Why isn't you application exiting when the `include` line is hit?

**Comment by casperisfine** [comment]
> Why isn't your application exiting when the `include` line is hit?

Probably because of https://github.com/rails/rails/issues/37650

**Comment by fxn** [comment]
@casperisfine ahhh, probably, yes.

**Comment by swistak** [comment]
>  Why isn't your application exiting when the include line is hit?

I was wondering exactly that. Also yes, it's in context of Rails 6, I'm sorry I've not specified it up-front.

**Comment by casperisfine** [comment]
@swistak can you try with Rails `6.0.2.1`, if I'm right the fix for the incorrect error rescuing issue should be in it.

That should make your app properly crash on boot.

**Comment by swistak** [comment]
Yup. Sure enough now I get:

`NameError: uninitialized constant ClassThatForSureDoesNotExist`

Thanks for the help.

**Comment by fxn** [comment]
👍
