### ISSUE TITLE
Zeitwerk broken by Bundler

### ISSUE THREAD

**Issue by Aquaj** [fxn/zeitwerk#104]
Hi, I think Zeitwerk's gets messed up by Bundler's `reverse_rubygems_kernel_mixin` internal method.

I'll do my best to explain the initial issue and what I've found so far.
On the app I'm working on we had an issue where Karafka wouldn't fail on launch (launched with `bundle exec foreman start karafka`), raising a `LoadError - file not found 'app/channels/application_cable'`. 
As the path is a folder and not an actual ruby file, it seems like it should've been autovivified instead of being `require`d by the app. So I went digging some more and it appears that even though the `require` method defined in lib/zeitwerk/kernel.rb is called at the beginning of the application initialization, as soon as the app reaches `config/application.rb` (more specifically `Bundler.require(*Rails.group)`), Bundler tries to setup, which includes a call to `reverse_rubygems_kernel_mixin`, resetting `Kernel#require` to its original version and overwriting Zeitwerk's modifications to it.

I don't really know how to fix it, and I don't know why we only encounter it when launching our karafka process and not on the rails server one, but I'm open to ideas on how we could solve this.

For now we had to resort to defaulting back on the `:classic` loader, which I'm not a big fan of but does the work.

I also have opened an issue on Bundler's repository (bundler/bundler#7553).

----
#### If you have the same issue and stumbled on this, here are some workarounds we've found:
- Falling back to the `:classic` autoloader (`config.autoloader = :classic` in `config/application.rb`)
- Using a binstub (`bundle binstub <library>`) in the Procfile for the library instead of the `bundle exec` call (`service: bin/<library>` instead of `service: bundle exec <library>`)

**Comment by fxn** [comment]
That is strange, Zeitwerk routinely works with Bundler in Rails applications and non-Rails Ruby projects.

Would it be possible for you to provide a minimal application that reproduces this?

**Comment by Aquaj** [comment]
I found it strange too.
As mentioned it's not happening with the server process, which part of what's making this so confusing.

I'll try to set up a minimal app replicating the issue during the week.

**Comment by Aquaj** [comment]
I set up a replicating app with as little as I could (by shaving away from my problem-encountering app). https://github.com/Aquaj/broken-zeitwerk-minimal-ex

As I worked on it I figured a few more things:
- It happens (apparently) because of a `require "config/environment"` in Karafka's boot file
- Without foreman it doesn't happen
- With a `karafka` binstub (instead of `bundle exec`) it doesn't happen
- Without Karafka (having foreman run `bundle exec ruby karafka.rb`) it doesn't happen

It seems to stem from a cocktail of libraries (Karafka, Foreman, Zeitwerk, Bundler) so it's likely a fix could be found in any of them, but since retrograding to the `:classic` autoloader fixes the issue, it still would be a regression for Zeitwerk.

I'll try to look into the issue more now that we have a minimal replicating case. There's no urgency to finding a fix though, as there are many ways to go around the issue.

**Comment by fxn** [comment]
Would it be possible for you to inspect

```ruby
Object.method(:require).source_location
```

in a few places to see it changed?

For example, in a vanillar shell you get this:

```
% irb
irb(main):001:0> Object.method(:require).source_location
=> ["/Users/fxn/.asdf/installs/ruby/2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb", 34]
irb(main):002:0> require "zeitwerk"
=> true
irb(main):003:0> Object.method(:require).source_location
=> ["/Users/fxn/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb", 13]
```

**Comment by Aquaj** [comment]
Sure !
I added the logging wherever I thought it might be useful.

I also added this snippet at the very beginning of the `foreman` binstub:
```
class Object
  def self.method_added(method_name)
    return unless method_name.to_s == 'require'
    puts "== REDEFINITION OF REQUIRE in Object"
    caller.first(3).each { |callsite| puts ' - ' + callsite }
    puts "=="
  end
end
module Kernel
  def self.method_added(method_name)
    return unless method_name.to_s == 'require'
    puts "== REDEFINITION OF REQUIRE in Kernel"
    caller.first(3).each { |callsite| puts ' - ' + callsite }
    puts "=="
  end
end

```
And here are the results
```
=[BINSTUB]= ["/Users/aquaj/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb", 34]
== REDEFINITION OF REQUIRE in Object
 - /Users/aquaj/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:61:in `<class:Runtime>'
 - /Users/aquaj/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:4:in `<module:Bundler>'
 - /Users/aquaj/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:3:in `<top (required)>'
==
== REDEFINITION OF REQUIRE in Kernel
 - /Users/aquaj/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/rubygems_integration.rb:605:in `define_method'
 - /Users/aquaj/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/rubygems_integration.rb:605:in `redefine_method'
 - /Users/aquaj/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/rubygems_integration.rb:355:in `block in reverse_rubygems_kernel_mixin'
==

karafka.1 | started with pid 90426
karafka.1 | =[KARAFKA]= ["/Users/aquaj/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/zeitwerk-2.2.1/lib/zeitwerk/kernel.rb", 13]
karafka.1 | =[ENVIRONMENT/PRE-REQ_REL]= ["/Users/aquaj/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/zeitwerk-2.2.1/lib/zeitwerk/kernel.rb", 13]
karafka.1 | =[APPLICATION/PRE-REQ_REL]= ["/Users/aquaj/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/zeitwerk-2.2.1/lib/zeitwerk/kernel.rb", 13]
karafka.1 | =[BOOT/PRE-REQ_BUNDLER]= ["/Users/aquaj/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/zeitwerk-2.2.1/lib/zeitwerk/kernel.rb", 13]
karafka.1 | =[BOOT/POST-REQ_BUNDLER]= ["/Users/aquaj/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/zeitwerk-2.2.1/lib/zeitwerk/kernel.rb", 13]
karafka.1 | =[APPLICATION/PRE-REQ]= ["/Users/aquaj/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb", 323]
karafka.1 | =[APPLICATION/POST-REQ]= ["/Users/aquaj/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb", 323]
karafka.1 | =[ENVIRONMENT/POST-REQ_REL]= ["/Users/aquaj/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb", 323]
karafka.1 | bundler: failed to load command: karafka (/Users/aquaj/.rbenv/versions/2.6.5/bin/karafka)
karafka.1 | LoadError: cannot load such file -- /Users/aquaj/Code/external/broken-zeitwerk-minimal-ex/app/channels/application_cable
```

**Comment by Aquaj** [comment]
So I guess the flow is:
- Initial `require` in Ruby's implementation
- Rubygems (already present at the start of the binstub)
- Revert by Bundler (Redefinition)
- Zeitwerk (nil => `zeitwerk/kernel.rb`)
- Bootsnap (`zeitwerk/kernel.rb`=> `bootsnap/load_path_cache/core_ext/kernel_require.rb`)
- ActiveSupport (`bootsnap/load_path_cache/core_ext/kernel_require.rb` => `active_support/dependencies.rb`)

ActiveSupport modifies it by including a module which then calls `super`, so ultimately it defaults to Bootsnap's implementation. Which renames the original require (into `require_without_bootsnap`) and uses it in its own implementation, so it should eventually fallback to Zeitwerk, according to this apparent flow.

**Comment by fxn** [comment]
Hey!

Zeitwerk decorates `require`, if some other code replaces `require` with a version that does not contain our decoration, that's not a bug in Zeitwerk.

This issue may be useful in a text search, and I'm curious and will personally try to understand what is happening, but since this is not a bug in Zeitwerk ---which routinely works together with Rails and Bundler,--- and since I like the issues and PRs counter to be 0 in this project, I prefer to close.

**Comment by Aquaj** [comment]
Hi !
Looping back on this in case people stumble on the issue through search engines: this bug was ultimately fixed in Bundler's code, so you should consider updating that if you're encountering it — if you can't, I advise looking at the workarounds mentioned in other earlier comments.
Here's the issue I had opened on bundler/bundler back then: [[Github]](https://github.com/rubygems/rubygems/issues/3270) and [[the PR for the fix]](https://github.com/rubygems/rubygems/issues/3270) if people are interested.

**Comment by swrobel** [comment]
@Aquaj what version of bundler has the fix?
