### ISSUE TITLE
Would accepting a `namespace` parameter to `Loader#setup` be super horribad?

### ISSUE THREAD

**Issue by Skudo** [fxn/zeitwerk#109]
Our current legacy-ish file structure almost adheres to the conventional file structure Zeitwerk expects, except that ours has a namespace folder _above_ the entry point, to say.

```
v1/loader.rb                          # loading starts here
v1/models/user.rb                     # V1::User
v1/controllers/users_controller.rb     # V1::UsersController
```

I understand that Zeitwerk expects the file structure to be

```
loader.rb                             # loading starts here
models/v1/user.rb                     # V1::User
controllers/v1/users_controller.rb    # V1::UsersController
```

and then, calling `loader.push_dir` with `models` and `controllers` is straightforward and works as expected.

If possible though, I would love to avoid having to move around hundreds of files into "the absolutely right place". My idea was to therefore have something like

```ruby
module V1; end

loader = Zeitwerk::Loader.new
loader.push_dir(v1_root_dir.join('controllers'))
loader.push_dir(v1_root_dir.join('models'))
loader.setup(namespace: V1)
```

to put all the classes and modules `Loader#setup` finds into the "right" module. I have a quick, dirty hack in `Loader#setup` that makes it work for me locally, but I have to find out how to make that work with `Loader#eager_load` still. Before delving deeper into that, I wanted to make sure whether

1. there is some better way to do what I want to do and
2. if there is not, if such a change/feature would even be fine with you.

If that's something that's acceptable to you, I'll go ahead and come up with a proper PR, including tests etc.; otherwise, I'm looking forward to hear if there's a way to achieve what I want without having to move around a lot of files.

(At least I wouldn't have to be worried about `require_relative` breaking afterwards, because Zeitgeist makes those obsolete.)

**Comment by fxn** [comment]
Let me think about the ramifications.

To help me understand the use case. Which is the whole structure of the project? Do you have a `v2` directory? Is this a web application? If yes, using which web framework?

**Comment by byroot** [comment]
Ref: https://github.com/fxn/zeitwerk/pull/11

For what it's worth, I'd like this feature ;)

**Comment by fxn** [comment]
My main issue is that I need a compelling reason to support it. And if I see a use case that is worthwhile, we still have the choice to define a global root namespace instead of doing it per root directory.

For example, gems are fine and are idiomatic having a top-level folder. If someone does not want to have that top-level directory... fine, but that is not the kind of code base this lib wants to support.

Let's see the use case of @Skudo in any case.

**Comment by Skudo** [comment]
I'm sorry for the late reply, guys. Thanks a lot for your feedback so far.

What I'm looking at here is business code that looks at files in a filesystem folder and processes them according to a given "configuration file", so there's no web context, at all.

Over the course of 15+ years, there have been three major versions for the specification of aforementioned "configuration" file and each time a new major version had been concocted, they just "forked" the code to a separate folder and implemented that new version in there. That's how we've ended up with this file structure, I was told:

```
src
|- v1
|  |- controllers
|  |- models
|  |- serializers
|  |- services
|
|- v2
|  |- controllers
|  |- models
|  |- serializers
|  |- services
|
|- v3
|  |- controllers
|  |- models
|  |- serializers
|  |- services
|
| # Snipped some factories.
|
| # These pretty much just contain a hot mess of `require_relative`.
|- v1.rb
|- v2.rb
|- v3.rb
```

As I've found a LOT of (often redundant) `require_relative` in places where they IMO shouldn't be – and because I've had good experiences with `zeitwerk`  in other projects –, I've wanted to use `zeitwerk` for the upcoming `v4`. I however didn't want to go all gung-ho and change the entire file structure of the project, if possible, but I understand the philosophy for `zeitwerk` to not support unconventional file structures and I'm totally behind that; especially if you'd asked me prior to being assigned to this legacy code.

**Comment by fxn** [comment]
Interesting.

Let me ask a few questions. Are v1 .. v3 in use under their respective namespaces or are those directories there just for historical reasons, but unused? Would you use Zetiwerk for all versions, or only v4? If the project depends on a configuration file, can you control file names will follow the expected conventions? Do you need reloading in this project? Could you do without `require_relative` for v4 (Zeitwerk does not support it).

**Comment by fxn** [comment]
Hey! I like to keep issues and PRs in this project to 0... are you still willing to discuss this?

**Comment by Skudo** [comment]
I'm sorry, I must have missed the notification that something happened in here.

> Are v1 .. v3 in use under their respective namespaces or are those directories there just for historical reasons, but unused?

Those namespaces are in use still; v1 is going to hit EOL soon, but v2 and v3 are going to be around for the foreseeable future, I'm afraid.

> Would you use Zetiwerk for all versions, or only v4? 

If the changes required to support existing code are minimal, I'd switch to using Zeitwerk for all of them, but if I can use it for v4, I'll be more than happy.

> If the project depends on a configuration file, can you control file names will follow the expected conventions? 

Yes.

> Do you need reloading in this project? 

No.

> Could you do without require_relative for v4?

Yes, definitely.

**Comment by fxn** [comment]
Thanks @Skudo. I need to think about it.

This could be seen as a change in the root namespace, or also as a need for allowing "holes" in the file structure, which is something that also shows up from time to time. In that other point of view, the root directory would be `src`, `v4` would be a namespace, and you'd want to jump over its subdirectories, so to speak.

@byroot's use case could only be solved configuring root namespaces though.

Will be out of town for a few days, but will eventually come back to this.

**Comment by byroot** [comment]
I think "allowing holes" would be more complex than allowing to specify the root namespace.

And even though Zeitwerk changed a lot since then, I think #11 was rather simple.

**Comment by fxn** [comment]
By now, my intuition tells me to go with the "holes" idea, since I've seen this one popping out several times already because some projects would like to use subdirectories for organizational purposes only.

I have implemented that [in this branch](https://github.com/fxn/zeitwerk/tree/skip). The API is `skip`, for lack of a better short name (vs `jump_over`, `not_a_namespace`, ...).

@Skudo in your project, you'd do the following:

```ruby
loader.push_dir("src")
%w(controllers models serializers services).each do |dir|
  loader.skip("*/#{dir}")
end
```

If in a first phase you do not want to migrate `v1..v3`, you could ignore them while focusing on `v4`:

```ruby
%w(v1 v2 v3).each do |vn|
  loader.ignore(vn)
end
```

Would you like to give that branch a try?

**Comment by Skudo** [comment]
Thanks a lot, I will give that branch a try tomorrow morning and I will report back soon after.

**Comment by Skudo** [comment]
It works like a charm!

Now I can't live without `Loader#skip` anymore.

**Comment by fxn** [comment]
Fantastic! I'll think a bit more about the name of the method, and will eventually merge and release 2.3. Let me leave this open until that happens.

**Comment by fxn** [comment]
2.3.0 is out, and the method is finally called `collapse`. Thanks for the discussion!
