### ISSUE TITLE
Is there a recommend version which supports Ruby 2.3.7?

### ISSUE THREAD

**Issue by MadBomber** [fxn/zeitwerk#110]
I'm working on some old legacy RoR code which is slowly being moved into the Rails 4.2.x range.  In the meantime, what is the last version of zeitwerk which will support Ruby 2.3.7?

Dewayne
  o-*

**Comment by rafaelfranca** [comment]
There is no version which supports Ruby 2.3. Zeitwerk needs a feature that was only implemented in Ruby 2.4

**Comment by fxn** [comment]
Note also that to use Zeitwerk in Rails you need at least Rails 6, which requires Ruby 2.5 or newer.
