### ISSUE TITLE
How can I define namespaces in the app directory?

### ISSUE THREAD

**Issue by LandonSchropp** [fxn/zeitwerk#112]
Apologies if this is answered in the documentation. I looked and couldn't find it.

Our application has a `types` directory where we define modules that contain some of our constants. I'd really like to be able to do this:

* `app/types/alarm.rb` → `Type::Alarm`
* `app/types/resolution.rb` → `Type::Resolution`

I think there are two components to this:

* I'd like to allow namespaces to be defined in some of my top-level directories inside of `app`. In this example, `app/type` (or, better yet, `app/types`) would hold the `Type` module namespace.
* It would be great to use a plural directory to define singular modules. However, if this isn't possible, it's not the end of the world.

Is there any way to configure Zeitwerk to make this work?

Thanks!

**Comment by fxn** [comment]
I don't think this is documented, it is an unusual pattern. But it is possible to use `app` as root directory.

You need first to add the directory to autoload paths in `config/application.rb`:

```ruby
config.autoload_paths << "#{Rails.root}/app"
```

OK, in theory that would mean that `app/models` defines a top-level `Models` namespace, but thanks to the [support for nested root directories](https://github.com/fxn/zeitwerk#nested-root-directories), that won't be the case, and the usual subdirectories in the autoload paths will work as always out of the box.

However, `app/assets` and `app/views` would be considered to define namespaces. It would be good to tell Zeiwerk to ignore them, also in `config/application.rb`:

```ruby
Rails.autoloaders.main.ignore("#{Rails.root}/app/assets")
Rails.autoloaders.main.ignore("#{Rails.root}/app/views")
```

The difference plural/singular stretches the conventions a bit, but technically it can be addressed with a custom inflector. Toss something like this in `config/application.rb` too:

```ruby
Rails.autoloaders.main.inflector = Class.new do
  def self.camelize(basename, abspath)
    abspath == "#{Rails.root}/app/types" ? "Type" : basename.camelize
  end
end
```

**Comment by LandonSchropp** [comment]
@fxn Thanks for the awesome and detailed reply!

It's good to know I can modify the plurality behavior by overriding the Zeitwerk inflector.

I'm still struggling to get a top-level `type` directory working. Here's what I have in `application.rb`:

```
config.autoload_paths << Rails.root.join("app")
config.eager_load_paths << Rails.root.join("app")
```

I've printed out the `autoload_paths` and they seem to be valid. I've defined a `Type::Access` class at `app/type/access.rb`:

```
module Type
  class Access
    extend Typeable

    READ = "read".freeze
    WRITE = "write".freeze
  end
end
```

However, if I start my console and type out `Type::Access`, I still get this error:

```
NameError (uninitialized constant Type)
```

Am I missing something here?

Thanks again for the help!

**Comment by fxn** [comment]
Ahhh, yes, I see.

Problem is that `app/type` belongs to the autoload paths, because all subdirectories of `app` except for a few known ones do automatically. So, Zeitwerk detects `app/type` is nested in `app` and the former wins.

Let me see if there is a clean solution, I suspect we may be missing APIs to change these defaults.

**Comment by LandonSchropp** [comment]
@fxn Have you had a chance to look into this? Thanks!

**Comment by fxn** [comment]
No.

**Comment by fxn** [comment]
Since this involves stuff that is specific to Rails, I have moved this one to https://github.com/rails/rails/issues/38725.

**Comment by LandonSchropp** [comment]
Thanks!
