### ISSUE TITLE
handling AppName::VERSION

### ISSUE THREAD

**Issue by modosc** [fxn/zeitwerk#114]
we have a rails app which is also a gem. we have this file in `lib/app_name/version.rb`:
```ruby
module AppName
  VERSION = '1.2.3
end
```

the `zeitwerk:check` task fails on this - we can make it pass by adding in `class Version; end` as a workaround but our tooling for bumping versions overwrites this file (and the hack feels dirty).

is there a config that supports both rails and the gemspec mode (which i assume allows this file to exist as-is)? thanks!

**Comment by fxn** [comment]
You've got to customize the inflector. In the case of Rails, please check [these docs](https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#customizing-inflections).

**Comment by modosc** [comment]
so the idea is to add something like `inflect.acronym "VERSION"`? is there a way to scope this somehow so it's only for `AppName::VERSION` and not everywhere else?

**Comment by fxn** [comment]
Yes, you could implement a custom inflector. The idea would be:

```ruby
app_version = "#{Rails.root}/lib/app_name/version.rb"
Rails.autoloaders.main.inflector = Class.new do
  def camelize(basename, abspath)
    abspath == app_version ? "VERSION" : basename.camelize
  end
end.new
```

I've written that off the top of my head, it's untested, but you see the idea.

**Comment by modosc** [comment]
great, i'll try it out next week. thanks!

**Comment by modosc** [comment]
@fxn that worked great, thanks again
