### ISSUE TITLE
undefined method `collapse' for Zeitwerk::Loader

### ISSUE THREAD

**Issue by adrianthedev** [fxn/zeitwerk#115]
Hi,

I'm getting a `undefined method `collapse' for #<Zeitwerk::Loader:0x00007fe820e4c270> (NoMethodError)`.

This is my code inside the main file in the `lib` directory of a Rails engine before all the `Module` code like instructed [here](https://github.com/fxn/zeitwerk#synopsis)
```
loader = Zeitwerk::Loader.for_gem
loader.collapse("tools/*")
loader.setup # ready!
loader.eager_load
```

What am I doing wrong? I can't find any way of making this work.

**Comment by fxn** [comment]
You need version 2.3.

**Comment by adrianthedev** [comment]
Got it. Will give it a try.

**Comment by adrianthedev** [comment]
Thank you!

**Comment by fxn** [comment]
However, that configuration is strange.

You seem to have a `lib` directory, and a `tools` directory at the same level. Collapsing makes sense only for directories at some level _below some root directory_.

**Comment by adrianthedev** [comment]
Oh, ok. I got it. The path is relative to the file. I assumed that it would collapse anything with `tools/*`.

Thank you for this.
Will try it and come back.

**Comment by fxn** [comment]
Perhaps you need something like

```ruby
loader.collapse("#{__dir__}/tools/*")
```
