### ISSUE TITLE
Zeitwerk 2.3 breaks nested mailers if there is a model of the same name in the project

### ISSUE THREAD

**Issue by brenogazzola** [fxn/zeitwerk#119]
I have a production Rails 6.0 app for which I keep a branch pointed to `master` so that I can fix any breaks as they show up and prepare for an eventual upgrade

5 days ago `master` upgraded to Zeitwerk 2.3 and now I have a problem where a few mailers are broken, looking for files that do not exist and are not being included or required anywhere.

Directory structure:
```
helpers/payments_helper

models/gift_registry
models/invitation

mailers/decoration/payment_mailer
mailers/gift_registry/payment_mailer
mailers/invitation/payment_mailer
```

Models:
```
class GiftRegistry < ApplicationRecord
end

class Invitation < ApplicationRecord
end
```

Helper:
```
module PaymentsHelper
end
```

Mailers:
```
class Decoration::PaymentMailer < ApplicationMailer
  helper PaymentsHelper

  def processed(payment)
  end
end

class GiftRegistry::PaymentMailer < ApplicationMailer
  helper PaymentsHelper

  def processed(payment)
  end
end

class Invitation::PaymentMailer < ApplicationMailer
  helper PaymentsHelper

  def processed(payment)
  end
end
```

Now, if I try to send a `processed` email from `Decoration` (for which there is no corresponding model), everything works:
```
irb(main):013:0> Decoration::PaymentMailer.processed Payment.last
=> #<Mail::Message:70230284153160
```

But if I try the same from `GiftRegistry` or `Invitation`, I get an error
```
irb(main):001:0> Invitation::PaymentMailer.processed Payment.last
Traceback (most recent call last):
        2: from (irb):1
        1: from app/mailers/invitation/payment_mailer.rb:3:in `<main>'
NameError (uninitialized constant #<Class:0x00007f96785ff2d8>::PaymentMailerHelper)
Did you mean?  Invitation::PaymentMailerPreview
```

If I repeat the same command, I get a different error
```
irb(main):002:0> Invitation::PaymentMailer.processed Payment.last
  Payment Load (0.7ms)  SELECT "payments".* FROM "payments" ORDER BY "payments"."id" DESC LIMIT $1  [["LIMIT", 1]]
Traceback (most recent call last):
        2: from (irb):2
        1: from (irb):2:in `rescue in irb_binding'
NoMethodError (undefined method `processed' for Invitation::PaymentMailer:Class)
```

So it seems the first time it tried to load a constant that does not exist in my project or rails, and is not included anywhere (`PaymentMailerHelper`). The second time it instead could not locate the method in the class.

To ensure there really was nothing wrong with the mailers themselves, I renamed the folder to `Invitatiom` and the class to `Invitatiom::PaymentMailer`. It worked:
```
Invitatiom::PaymentMailer.processed Payment.last
=> #<Mail::Message:70142181082160
```

So, what is breaking here? Zeitwerk 2.2 is fine with this, but Zeitwerk 2.3 doesn't like this structure.

**Comment by fxn** [comment]
Thanks for keeping track of `master`, early feedback like this is awesome.

I believe it is unlikely that 2.3 introduces this, because the only thing that it does is supporting eager load after reload (touching a flag), and collapsing directories (new feature that your app probably does not use).

However, at about the same time, we removed `require_dependency` calls from `helper` in [this commit](https://github.com/rails/rails/commit/5b28a0e972da31da570ed24be505ef7958ab4b5e). That change could be a suspect too.

Upgrade to Zeitwerk 2.3 was [this commit](https://github.com/rails/rails/commit/cf713096849d263b9ae9c7ac3a77d5fd84fa2db0).

Could you check both SHA1s to see which one of them introduces the problem?

**Comment by casperisfine** [comment]
@fxn that's definitely the `require_dependency` change, I had the same error when doing our weekly rails bump.

That's why I opened https://github.com/rails/rails/pull/39140

**Comment by fxn** [comment]
Ahhh, fantastic! Let's close here then.

**Comment by brenogazzola** [comment]
Oh, sorry about this. Since it was a dependency problem, when I was looking through the changes I saw the Zeitwerk bump and thought the new directory collapse might be the cause (since the mailers were inside other directories).

**Comment by fxn** [comment]
No prob! Thanks for trying `master` again!

**Comment by fxn** [comment]
Hey @brenogazzola, this should be fixed in `master` now, could you give it a try?

**Comment by brenogazzola** [comment]
Tested on ruby versions `2.5.8`, `2.6.6` and `2.7.0`. They are all working again. Thanks!

**Comment by fxn** [comment]
Awesome, thank you! ❤️
