### ISSUE TITLE
zeitwerk requires Ruby version >= 2.4.4

### ISSUE THREAD

**Issue by codemicky** [fxn/zeitwerk#120]
One of my Ruby projects use Ruby 2.4.3
I am getting this issue.

`	There are no versions of zeitwerk (~> 2.2, >= 2.2.2) compatible with your Ruby & RubyGems. Maybe try installing an older version of the gem you're looking for?
	zeitwerk requires Ruby version >= 2.4.4. The current ruby version is 2.4.3.205.`

How can I fix this issue?

**Comment by fxn** [comment]
Hi @codemicky. The library cannot work with Ruby 2.4.3, it depends on a feature that was added in 2.4.4 (that `require` stores real paths in `$LOADED_FEATURES`).

If you want to use Zeitwerk, you need to upgrade Ruby to at least 2.4.4.

Let me say also that Ruby 2.4 [has reached its EOL](https://www.ruby-lang.org/en/downloads/branches/), so upgrading to 2.5 would be even a better idea if possible. At some point, Zeitwerk won't support 2.4.

**Comment by codemicky** [comment]
@fxn, thanks for your reply. 
I see.
I will upgrade my project from Ruby 2.4.3 to 2.4.4

Thank you. 👍
