### ISSUE TITLE
Custom namespaces in Rails

### ISSUE THREAD

**Issue by der-flo** [fxn/zeitwerk#134]
The [ability to specify a `namespace` keyword parameter in `#push_dir`](https://github.com/fxn/zeitwerk/blob/master/lib/zeitwerk/loader.rb#L196) is very interesting.  Unfortunately [Rails seems to not support this feature](https://github.com/rails/rails/blob/8237c4d33035bd131865f1e73577748892a75f0a/activesupport/lib/active_support/dependencies/zeitwerk_integration.rb#L87).

This could clean up a directory hierachy like `<RAILS_ROOT>/modules/my_mod/app/models/my_mod/class1.rb` to `<RAILS_ROOT>/modules/my_mod/app/models/class1.rb` etc.

@fxn : Do you know of a workaround to reach this?

**Comment by fxn** [comment]
Hey!

Zeitwerk is a generic library and this question is Rails-specific. I have created https://github.com/rails/rails/issues/40126 for it.
