### ISSUE TITLE
Disappearing instance methods

### ISSUE THREAD

**Issue by morgoth** [fxn/zeitwerk#14]
During upgrade to Rails 6.0.0.beta2 I found a problem with zeitwerk autoloader, which results in non present instance methods on controller that actually is defined and works fine with "classic" autoloader.

I reproduced it here https://github.com/morgoth/bug with steps described in the readme.

Maybe it's more a Rails problem, but since it strictly connects with switching autoloader I'm opening it here.

**Comment by fxn** [comment]
I have seen at least something. This module is not right

```ruby
module Admin::ApplicationHelper
  include ButtonHelpers
end
```

because `Admin` is not in the nesting. Ruby does not look for `Admin::ButtonHelpers` there.

This one is good, because `:classic` mode does look into `Admin` and does _not_ match Ruby semantics.

**Comment by morgoth** [comment]
Yes, that's fine and fixing it is easy if you actually get the correct error message.
What is misleading is raising this no method error, but I guess this is caused by Rails somehow.

I'm pretty sure that someone will be bitten by this as well. Shall I open an issue on Rails?

**Comment by fxn** [comment]
My conjecture is that someone has shallowed that error, and that one is not Zeitwerk. Would be surprised if it is Rails, but who knows.

Therefore, the class was defined, but in the middle of its body execution this error happened and was shallowed by someone, and the program continued with a half-defined `Admin::ApplicationController`.

That is the ultimate explanation, `Admin::ApplicationController` got defined, but the interpretation of its class body interrupted, so the methods didn't really get defined.

**Comment by morgoth** [comment]
Also note the difference when reaching this code via rails server and rails console/runner. In the first case you get this misleading error, in second case all is clear, so maybe some error middleware in Rails stack is causing this...

**Comment by fxn** [comment]
Let's find out, it should bubble up.

**Comment by fxn** [comment]
The problem is [here](https://github.com/rails/rails/blob/f4a30d2a0706f278a20c63a3d99288de79b52e5f/actionpack/lib/action_dispatch/http/parameters.rb#L100-L104). That code shallows the `NameError` raised.

Could you please open an issue in the Rails project? To avoid confusion with autoloading (which we've seen it is unrelated), you could just use `NOT_DEFINED_CONSTANT_SHOULD_RAISE_NAME_ERROR` in that helper.
