### ISSUE TITLE
Document best practice for monkey-patches

### ISSUE THREAD

**Issue by manueljacob** [fxn/zeitwerk#141]
I’m using Zeitwerk in a gem that defines some classes alongside `String` monkey-patches to enable easy construction of these classes. Since the point of the gem is to define a DSL and its users are expected to do not much else than using the DSL, it makes sense to have global monkey-patches instead of using refinements.

So far, I was defining each `String` monkey-patch in the file that defined the class that’s instantiated by the monkey-patch. However that requires referencing the class mainly defined by that file or explicitly requiring that file, which defeats to point of using an autoloading framework.

What would be a better option?

- Use eager loading? Given the current small size of the gem, it would probably not decrease performance, but in the future the gem might grow and users of the gem might want to use only a part of it.
- Explicitly require the files containing the monkey-patches from the top-level gem source file? To continue to use lazy-loading, the monkey-patches must be moved somewhere else (maybe this is a good idea anyway), into separate or combined files. These files would not conform to the conventional file structure. What needs to be done to not confuse Zeitwerk?

I think it would be good to document best practices for these kind of use cases (and more general ones). If you think my use case is too niche, I would appreciate some pointers for the concrete use case.

**Comment by fxn** [comment]
Hey Manuel! Could you show me some example files and gem structure to better understand the use case?

**Comment by manueljacob** [comment]
Thank you Xavier for the quick answer!

I set up a minimal example reflecting my current structure:

`lib/example.rb`:

```ruby
require 'zeitwerk'

loader = Zeitwerk::Loader.for_gem
loader.setup

module Example
end
```

`lib/example/foo.rb`:

```ruby
module Example
	class Foo
		def initialize(s)
			@s = s
		end
	end
end

class String
	def foo
		Example::Foo.new(self)
	end
end
```

The gem is supposed to be used like this:

```ruby
require 'example'
…
foo = 'asdf'.foo
…
```

**Comment by fxn** [comment]
I see!

At first sight, I'd say the natural way to be lazy here is to base autoloading on `method_missing`. Mod details, when `String#foo` is called you know your gem provides it and load `lib/example/foo.rb`. This can be done with a bare `require` without Zeitwerk if the project follows a convention method name -> file name and files are self-contained.

On the other hand, eager loading is a very common use case for Zeitwerk in gems. In order to be able to eager load without `require`, you need autoloading in place in the general case, because constants could be used at the top-level. That is the point.

Eager loading would definitely be simpler. You need to consider the user gets all monkey patches defined, instead of cherry-picking. If that's not an issue, I'd go with eager loading, with the information that I have.

**Comment by manueljacob** [comment]
In this particular context, it makes sense from a user perspective to have all monkey-patches defined when the gem is loaded. The monkey-patches are very small and unlikely to be more than 10 at any point of the development of that gem. Therefore it makes sense to eager load them (overriding `method_missing` seems overkill). To continue to be able to use lazy-loading for the classes instantiated by the monkey-patches, the monkey-patches would need to be separate. Where do I put the monkey-patches to ensure that

- Zeitwerk doesn’t get confused because of the non-conventional names (at least I’m not aware of a convention for monkey-patches), and
- the monkey-patches get eager-loaded (a simple `require` would be fine for one combined file, but it would violate the DRY principle if there are more files), and
- the rest of the code is lazy-loaded?

**Comment by fxn** [comment]
If you eager load, you can keep the monkey patches where they are now (assuming the gem does not use the monkey patches itself at the top-level).

**Comment by fxn** [comment]
Hey, did you have the chance to find a solution that suits the project?

It is a too specific case to be documented, the solution itself is tailor-made for your gem and not generalizable. So, when you get the gem working in a way you like, we'd close here. Like to have 0 issues.

**Comment by fxn** [comment]
Hey! I am going to close. Please, if you need more help do not hesitate to followup or contact me directly (email in GitHub bio).
