### ISSUE TITLE
Feature Request: Zeitwerk.on_load

### ISSUE THREAD

**Issue by casperisfine** [fxn/zeitwerk#142]
### Context

It is very common in Rails apps, to set configuration values on module / classes from either `config/environments/*.rb` or `config/initializers/*.rb`. e.g.:

```ruby
# some/autoloaded/file.rb
class SomeApiClient
  class << self
    attr_accessor :endpoint
  end
end
```

```ruby
# config/environments/development.rb
config.to_prepare do
  SomeApiClient.endpoint = 'https://my-api.dev'
end
```

```ruby
# config/environments/production.rb
config.to_prepare do
  SomeApiClient.endpoint = 'https://my-api.com'
end
```

### Problem

Because of this pattern, a lot of code that should be lazy loaded, end up eager loaded. Assuming part of this code won't be used in the development request, or test case, it means time is wasted loading "useless" code.

### Proposal

I think `zeitwerk` could offer an API to get a callback when a namespace is loaded, [similar to `ActiveSupport::LazyLoadHooks`](https://api.rubyonrails.org/classes/ActiveSupport/LazyLoadHooks.html), e.g.:

```ruby
# config/environments/development.rb
Zeitwerk.on_load('SomeApiClient') do |client|
  client.endpoint = 'https://my-api.dev'
end

# or

Zeitwerk.on_load('SomeApiClient') do
  SomeApiClient.endpoint = 'https://my-api.dev'
end

# or

Zeitwerk.on_load('SomeApiClient') do
  self.endpoint = 'https://my-api.dev'
end
```

@fxn what do you think?

cc @rafaelfranca @etiennebarrie

**Comment by fxn** [comment]
Let me think about it.

In principle, the way 3rd-party dependencies load their code is private. In that sense, a global callback does not seem to match. At first right I see it per loader.

What do you think about this point?

**Comment by casperisfine** [comment]
> What do you think about this point?

I'd need to think about it more, but right now I think:

  - The callback key is a constant names, and constants are global to the ruby process. 
  - It might be a bit annoying to have to find a gem's Zeitwerk loader to register a callback on it. How would that even work?
  - To be honest I was only thinking about in app code, so per loader would be fine to me, at least today.

**Comment by fxn** [comment]
> The callback key is a constant names, and constants are global to the ruby process.

Yes, but in the general case, the fact that the main interface is `Zeitwerk.on_load("AnotherApp::Foo")` seems suspicious, in the general case you're not supposed to know how does AnotherApp loads its code. That's what makes me think at which level this should be.

**Comment by casperisfine** [comment]
>  in the general case you're not supposed to know how does AnotherApp load its code.

Indeed. To be clear I'd be fine with a `Loader` base API, but I'm trying to argue against myself here in case we might miss other people use case.

I don't think users really care (nor should care) wether a constant is loaded by Zeitwerk or something else. As a user I could easily consider than Zeitwerk isn't just an application/library loader, but the global namespace manager.

You could easily have a situation were a non-zeitwerk dependency is loaded by a zeitwerk managed file, e.g.:

```ruby
# app/models/foo.rb

require "big-gem-that-is-slow"
...
```

In such case you'd want an `on_load('BigSlowGem')`, doesn't matter that it isn't loaded by Zeitwerk.

But maybe that feature would make more sense as a standalone library, however it might need to hook itself into Zeitwerk.

**Comment by fxn** [comment]
Hey @casperisfine! I am implementing this, I'll share a branch soon.

**Comment by fxn** [comment]
Implemented in https://github.com/fxn/zeitwerk/tree/on_load (at the instance level).

I'll add documentation to the README later. But you can try it if you'd like to.

**Comment by byroot** [comment]
Thanks ! I'll experiment with it soon and report back.

**Comment by casperisfine** [comment]
So, something I totally forgot to mention in the spec, is that I think `Loader#on_load` should:

  - Immediately call the callback if the constant is already loaded
  - Raise if it doesn't manage that constant.

Not sure if the later is possible though, I'll have to explore that.

**Comment by casperisfine** [comment]
Quick very early report on my experiment:

To test I just used this on a single namespace:

```ruby
# config/environments/development.rb
  if ENV['ONLOAD']
    Rails.autoloaders.main.on_load('BillingApi::Connection') do
      p [:config]
      BillingApi::Connection.use_billing_application = DevelopmentSupport::HostDetection.dev_service_running?(:billing)
      DevelopmentSupport::BillingApiPredictions.init
    end
  else
    config.to_prepare do
      p [:config]
      BillingApi::Connection.use_billing_application = DevelopmentSupport::HostDetection.dev_service_running?(:billing)
      DevelopmentSupport::BillingApiPredictions.init
    end
  end
```

```bash
$ DISABLE_SPRING=1 bin/rails runner 'p $LOADED_FEATURES.size; BillingApi::Connection'
[:config]
9926
$ ONLOAD=1 DISABLE_SPRING=1 bin/rails runner 'p $LOADED_FEATURES.size; BillingApi::Connection'
9878
[:config]
```

So we can see that:
  - The load of that namespace was properly delayed
  - The configuration block was properly called when the namespace was reference
  - With just this one line of change it prevented `48` files to be loaded.

However:

  - `Rails.autoloaders.main.on_load('BillingApi::Connection')` is quite verbose, it might require some integration on the Rails side to make it easier to use.
  - You have to know wether the namespace is handled by `autoloaders.main` or `autoloaders.once`, that's very easy to get wrong.

**Comment by fxn** [comment]
Yes, Rails integration would be the next step.

**Comment by casperisfine** [comment]
> Rails integration would be the next step.

Sounds good. 

So what's you opinion on this? Do you think it makes sense? Is there something else you'd like me to explore?

**Comment by fxn** [comment]
Nope! It is enough, thanks man!

I need to think about this a bit, there are several topics.

I thought about this as an event. If the constant is loaded, fine, you missed the event. So generally speaking you'll configure this before `setup` as everything else (but did not want to enforce it to play well with reloading and new files.). On the other hand, it would be a mistake to execute `loader.on_load("String")`, this loader has not loaded that class, and if reloading is disabled, we do not keep track of what we autoload. So, _if_ the loader loads something with that name, your code will be executed, otherwise it won't (that includes typos, we generally do not know what we manage).

In that sense, the Rails integration could define the callback for both loaders. That also plays well with the interpretation above.

User expectations can be set clear with documentation.

**Comment by casperisfine** [comment]
> If the constant was already loaded, fine, you missed the event. So generally speaking you'll configure this before `setup` as everything else

My first reaction is that this sound a bit too much like a footgun. Hence why I suggested:

> Immediately call the callback if the constant is already loaded

You could have a situation where a callback works just fine for a while, but then a later change make it referenced earlier than it was and the callback is no longer executed.

But I guess it might not be such a big problem if you only define these at the same time that you configure the loader. Maybe raising an error if you try to add callbacks after the setup phase would make it safer?

> if the loader loads something with that name, your code will be executed, otherwise it won't (that includes typos, we generally do not know what we manage).

Hum, I was about to suggest that when eager loading we could raise an error if some callbacks where not executed. But then it would render your suggested Rails API impossible to implement.

**Comment by fxn** [comment]
So, I have the feeling that this API is good enough, but it has some compromises.

Now, let me throw something totally different and out of the scope of Zeitwerk. What about a generic feature that works with files like

```ruby
on_require(path) do
  ...
end
```

?

**Comment by casperisfine** [comment]
> Now, let me throw something totally different and out of the scope of Zeitwerk.

Yes, as mentioned earlier, I'm actually wondering if this feature would make sense as totally independent of Zeitwerk, with maybe just an integration for performance.

> What about a generic feature that works with files

IMHO, working with paths is much more error prone and unpleasant than working with namespaces. It's not uncommon to move a namespace from a file to another. When you rename a class, you tend to grep for that name to update the references, not so much for file names.

Also it would be way less granular, because the only usable hook point would be on the return of the `require/load/etc` function, so the callback would be executed much later.

e.g.

```
# config.rb
on_require('a.rb') do
  A.config = 42
end

# a.rb
require 'b'

class A
  cattr_accessor :config
end

# b.rb
class B
  @config = A.config
end
```

In such scenario the callback happened too late.

**Comment by fxn** [comment]
I believe you can create similar edge cases for `on_load` if you contort the dependencies enough, in the end, you do not control what happens while the file loads.

In both techniques, what you implement has to agree with the logic of the technique. For example, with `on_load`, if you want to set a config via the callback and at the same time use the config at the class-level. Well, you cannot do it that way :).

Those are remarks only to iterate the topic in our heads, I believe the callback is useful and will ship it soon.

**Comment by casperisfine** [comment]
> I believe the callback is useful and will ship it soon.

Awesome! Thanks so much. Let me know if you'd like a review or something.

**Comment by fxn** [comment]
@casperisfine There we go! https://github.com/fxn/zeitwerk/pull/144
