### ISSUE TITLE
Issues with Ruby 3 and loading standard lib rexml/document

### ISSUE THREAD

**Issue by DannyBen** [fxn/zeitwerk#148]
I am not 100% sure this is zeitwerk's fault, but in case it is, here is the problem I see:

After upgrading from Ruby 2.7 to Ruby 3, all my rails applications that require `rexml/document` somewhere, fail with this error:

```
LoadError:
       cannot load such file -- rexml/document
     # /usr/share/rvm/gems/ruby-3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb
:34:in `require'
     # /usr/share/rvm/gems/ruby-3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb
:34:in `require'
```

This `rexml/document` is from Ruby's standard library.

Although I was unable to reproduce it in a non-rails setup (probably because I am not sure how zeitwerk is implemented in rails exactly), the below steps reproduce the problem.

### Reproduction Steps

When running this in Ruby 3.0, it fails, and in Ruby 2.7 it succeeds.

#### 1. Create a new minimal rails app

```
$ rails new myapp --minimal
$ cd myapp
```

#### 2. Create the file `config/initializers/xml.rb` and place this content in it:

```ruby
require 'rexml/document'
```

#### 3. Run the server to see the error

```
$ rails server
```

#### 4. Output

```
=> Booting Puma
=> Rails 6.1.0 application starting in development
=> Run `bin/rails server --help` for more startup options
Exiting
/usr/share/rvm/gems/ruby-3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in
`require': cannot load such file -- rexml/document (LoadError)
        from /usr/share/rvm/gems/ruby-3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/ker
nel.rb:34:in `require'
        from /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.0/lib/active_
support/dependencies.rb:332:in `block in require'

... trimmed ...
```

**Comment by fxn** [comment]
Zeitwerk manages code in its root paths only, the rest is loaded as usual. You see `zeitwerk` in the stack trace because it has a [thin wrapper around `require`](https://github.com/fxn/zeitwerk/blob/92fa501618253061154f903962f2dda3eb527c24/lib/zeitwerk/kernel.rb), but that is transparent.

To reproduce this issue without Rails take for example:

```ruby
require 'bundler/inline'

gemfile do
  source "https://rubygems.org"
end

require "rexml/document"
```

You'll get

```
cannot load such file -- rexml/document (LoadError)
```

Reason is `rexml` is a bundled gem in Ruby 3, so you need to add it as a dependency:

```ruby
require 'bundler/inline'

gemfile do
  source "https://rubygems.org"
  gem "rexml"
end

require "rexml/document" # => true
```

**Comment by DannyBen** [comment]
Oh cool. Thanks for the quick reply.

**Comment by jlecour** [comment]
I have had the same issue with "Open3". Adding "rexml" and "open3" in the Gemfile solved this.
