### ISSUE TITLE
What to do about files that don't define a corresponding constant?

### ISSUE THREAD

**Issue by natematykiewicz** [fxn/zeitwerk#151]
We have some files that don't define a corresponding constant to the file path. I'm upgrading a Rails app and enabling Zeitwerk. There's a few spots in `config/application.rb` or an initializer that require a file (using require_relative).

```
require_relative '../../../lib/foo/bar'

$ rake zeitwerk:check
Hold on, I am eager loading the application.
rake aborted!
NameError: uninitialized constant Foo::Bar
```

One example is a file called 'exceptions.rb'. It defines a bunch of custom exception classes in the namespace of the app. Very similar to what [active_record/errors.rb](https://github.com/rails/rails/blob/v6.0.3.4/activerecord/lib/active_record/errors.rb) does. This throws an `uninitialized constant Exceptions` error. It was pretty tricky to figure out what was going on since I agree that no "Exceptions" constant has been defined, so I was unsure of what was requiring it. Another example is a file that gets required that acts more like a ruby script -- it just reads some ENVs and calculates a constant. Since the ENVs don't change through the life of the app, these files don't need to be reloaded.

Here's a backtrace to the error:
```
/home/vagrant/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:409:in `const_get'
/home/vagrant/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:409:in `block (2 levels) in eager_load'
/home/vagrant/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:733:in `block in ls'
/home/vagrant/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:725:in `foreach'
/home/vagrant/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:725:in `ls'
/home/vagrant/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:404:in `block in eager_load'
/home/vagrant/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:393:in `synchronize'
/home/vagrant/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:393:in `eager_load'
/home/vagrant/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:508:in `each'
/home/vagrant/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:508:in `eager_load_all'
/home/vagrant/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/tasks/zeitwerk.rake:11:in `block in <top (required)>'
/home/vagrant/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/tasks/zeitwerk.rake:47:in `block (2 levels) in <top (required)>'
/home/vagrant/.rvm/gems/ruby-2.6.5/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/home/vagrant/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:22:in `eval'
/home/vagrant/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:22:in `<main>'
Tasks: TOP => zeitwerk:check
```

Thanks for all your work on Zeitwerk!

**Comment by fxn** [comment]
Hey! I understand `lib` is in the autoload paths?

**Comment by natematykiewicz** [comment]
It is! Should it be?

**Comment by fxn** [comment]
Nowadays, when people want to have reloadable code `app/lib` is a choice that works better, but anyway, I asked just to understand the situation, `lib` is technically fine.

If you have `lib` in the autoload paths to be able to autoload and reload from it, but there are some exceptions, you can tell Zeitwerk about them. Just throw in an initializer

```ruby
Rails.autoloaders.main.ignore("#{Rails.root}/lib/foo/bar.rb")
```

It is also a good practice to tell Zeitwerk to ignore subdirectories that are not meant to be Ruby namespaces, for example:

```ruby
Rails.autoloaders.main.ignore("#{Rails.root}/lib/tasks")
```

There is more documentation about ignoring parts of a project [here](https://github.com/fxn/zeitwerk#ignoring-parts-of-the-project).

**Comment by natematykiewicz** [comment]
This helped me solve my problem! Thanks.
