### ISSUE TITLE
"for_gem"-like VERSION inflection when using standard loader

### ISSUE THREAD

**Issue by taylorthurlow** [fxn/zeitwerk#152]
I'm using Zeitwerk in a gem which uses a third-party top-level namespace, so I need to use the standard loader instance instead of the `for_gem` one. This is fine, but it does impact the `VERSION` constant auto-loading.

I'm not seeing a way to replicate the `for_gem` VERSION inflection without impacting other classes/modules potentially named `version.rb` - I'd like to inflect _only_ `lib/foo/bar/version.rb` to `Foo::Bar::VERSION`. I have to make the choice to inflect _all_ `version.rb` files to `VERSION`. The gem inflector treats this as a special case which I don't think I can replicate easily with Zeitwerk's public API.

Is there something obvious that I'm missing or is this use case just not accounted for?

Thanks for your time!

**Comment by fxn** [comment]
For this you need a [custom inflector](https://github.com/fxn/zeitwerk#custom-inflector). `camelize` receives the absolute path in the second argument to help you be more precise. For example:

```ruby
class MyInflector < Zeitwerk::Inflector
  def camelize(basename, abspath)
    if abspath.end_with?("foo/bar/version.rb")
      "VERSION"
    else
      super
    end
  end
end
```

Then, configure that one:

```ruby
loader.inflector = MyInflector.new
```

**Comment by taylorthurlow** [comment]
Thanks for the clarification.
