### ISSUE TITLE
Benchmarking loads

### ISSUE THREAD

**Issue by ngan** [fxn/zeitwerk#154]
Hi, we're looking into benchmarking how long it takes various namespaces to be loaded. Does Zeitwerk have anything to hook into to get these figures? This is mainly for app-booting/CI measurements.

**Comment by fxn** [comment]
Is that a Rails application?

**Comment by ngan** [comment]
Yep. A rails app. We split our domains up and namespace everything. Trying to figure out if any team that owns a domain is doing something bad to cause app boot time to be slow.

**Comment by fxn** [comment]
When Rails boots in `development`, no application code is autoloaded. Code from dependencies is not managed by Zeitwerk.

**Comment by fxn** [comment]
Well, as a rule of thumb. Technically you can have installed init hooks like `to_prepare`, but to give you a rule of thumb

```
bin/rails runner 1
```

will generally load no application code because Zeitwerk is lazy.

**Comment by casperisfine** [comment]
I suspect they're interested about load time of namespace in eager load mode.

I see two ways to go about this:

  - Ultimately Ruby respect `Kernel#require`, so you can probably decorate that to get your timings.
  - I'd recommend to simply boot your app with stackprof or other profiler.

**Comment by fxn** [comment]
Depending on the details, it might be relevant to know that Zeitwerk [eager loads](https://github.com/fxn/zeitwerk/blob/c352092583c7bba99c8a9047f0454c32ba10c18c/lib/zeitwerk/loader.rb#L392-L420) using a breadth-first traversal. That is, it first eager loads top-level constants, then top-level of namespaces, and so on. Cross-references in top-level executable code may force jumps to other branches, though.

Anyway, let's see the Rails environment you are interested in, understand that loading what's in your Gemfile takes a great deal of time in relative terms for many apps of regular size, and ultimately the goal in measuring this.

**Comment by ngan** [comment]
Thanks for the help everyone. Yes, I would be eager loading the app to profile. Since we put our domains in separate dirs, I suppose I can take @casperisfine’s advice then sum up things by directory.
