### ISSUE TITLE
Recommendation for handling initializer and autoloaded constants

### ISSUE THREAD

**Issue by ngan** [fxn/zeitwerk#155]
I was reading through https://github.com/fxn/zeitwerk/issues/142 and thought it might be useful for my situation:

In `config/initializers/something.rb`
```ruby
Rails.autoloaders.main.on_load('SomeAutoloadedConstant') do
  SomeOtherLibrary.logger = SomeAutoloadedConstant.new
end
```

But, obviously, when I boot the app, that block doesn't run because, well, `SomeAutoloadedConstant ` is lazy loaded. Which means `SomeOtherLibrary.logger` evaluates to `nil`. So does that mean I have to do something like this?

```ruby
Rails.autoloaders.main.on_load('SomeAutoloadedConstant') do
  SomeOtherLibrary.logger = SomeAutoloadedConstant.new
end
Rails.application.config.after_initialize do
  SomeAutoloadedConstant
end

# or...

Rails.autoloaders.main.on_load('SomeAutoloadedConstant') do
  SomeOtherLibrary.logger = SomeAutoloadedConstant.new
end
Rails.autoloaders.main.preload(Rails.root.join('app/services/some_autoloaded_constant.rb'))
```

Which seems a bit silly. Am I suppose to resort to `to_prepare` here?

```ruby
Rails.application.config.to_prepare do
  SomeOtherLibrary.logger = SomeAutoloadedConstant.new
end
```

Which seems heavy-handed. I want to just set it once when it loads and reset it if and only if `SomeAutoloadedConstant` is reloaded. From what I understand, `to_prepare` _always_ runs on every request in development.

**Comment by ngan** [comment]
I was thinking, it would be nice to have an option to immediately constantize the constant. So you can do something like this:

```
Rails.autoloaders.main.on_load('SomeAutoloadedConstant', preload: true) do
  SomeOtherLibrary.logger = SomeAutoloadedConstant.new
end

```

**Comment by fxn** [comment]
Hi! You have to do it this way:

```ruby
Rails.application.reloader.to_prepare do
  SomeOtherLibrary.logger = SomeAutoloadedConstant.new
end
```

That is documented in the [Rails guide](https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#autoloading-when-the-application-boots) because it is specific to Rails logic.

**Comment by ngan** [comment]
Thanks for the info @fxn -- awesome as always.
