### ISSUE TITLE
Better support for adapter pattern and optional source files in general (never eager load instead of ignore totally)

### ISSUE THREAD

**Issue by skalee** [fxn/zeitwerk#16]
## Background

Adapter is a popular design pattern in Ruby. Quite often, adapters rely on some optional dependencies, for example Active Record's `SQLite3Adapter` starts with following lines:

```ruby
gem "sqlite3", "~> 1.3", ">= 1.3.6"
require "sqlite3"
```
([from rails/rails](https://github.com/rails/rails/blob/4353adab89bab252521e0e191d0177ece1538fbb/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb#L12-L13))

Consequently, adapter source file must be loaded conditionally, which isn't fully supported by Zeitwerk — not when a gem or application is supposed to be loaded eagerly. Zeitwerk's README explains how to workaround it:

> On the other hand, if your code is eager loaded by you or a parent project (with Zeitwerk::Loader.eager_load_all), those require calls are going to be executed. Ignoring the adapters prevents that:
> 
> ```ruby
> db_adapters = "#{__dir__}/my_gem/db_adapters"
> loader.ignore(db_adapters)
> loader.setup
> ```
>
> The chosen adapter, then, has to be loaded by hand somehow:
>
> ```ruby
> require "my_gem/db_adapters/#{config[:db_adapter]}"
> ```

However, this basically means: do not use Zeitwerk for adapters at all. Switch back to old `require` instead, and resign from all the benefits Zeitwerk provides, including code reloading. I believe this could be improved.

## Proposal

IMHO optional source files should be handled by Zeitwerk. The only thing what must be done in order to resolve this problem is to exclude them from being loaded eagerly. My proposal is to define a method `Loader#exclude_from_eager_loading`, which would work as in a following example:

```ruby
db_adapters = "#{__dir__}/my_gem/db_adapters"
loader.exclude_from_eager_loading(db_adapters)
loader.setup
```

Then, given there is an adapter named `MyGem::DbAdapters::MyAdapter` defined in a source file `my_gem/db_adapters/my_adapter.rb`:

- calling `loader.eager_load` would not load that source file;
- referencing `MyGem::DbAdapters::MyAdapter` would load that source file, regardless if `loader.eager_load` has been called previously or not;
- calling `loader.preload("my_gem/db_adapters/my_adapter.rb")` would also load that source file;

Also, perhaps it's worth to add an argument to `#eager_load` method, so that:

- calling `loader.eager_load(optional: true)` would load that source file as well;

WDYT?

**Comment by fxn** [comment]
Yes, that is a conscious trade-off.

This idea was implemented in the [initial commit](https://github.com/fxn/zeitwerk/commit/60e69187902203482660e382a32674403676e7a9):

<img width="848" alt="screenshot 2019-03-08 at 08 22 46" src="https://user-images.githubusercontent.com/3387/54014004-774f9d80-417b-11e9-8c94-1d7afdf6fd4b.png">

but further discussions made me consider [removing it](https://github.com/fxn/zeitwerk/commit/a1bd83b10521f41f7f74e921602839a1813d11e4).

In addition to that, I expect that kind of patterns to be more common in gems than in services. Gems normally do not reload. You program and run the test suite. And adapters are normally a tiny % of the code base, so one or two exceptional `require` calls are an acceptable compromise, generally speaking.

**Comment by fxn** [comment]
Closing by now... time will tell. Thanks anyway for the issue!

**Comment by skalee** [comment]
For anyone who has came here by chance, time has told ten days later. See #22.

**Comment by fxn** [comment]
Indeed 😀.
