### ISSUE TITLE
Failed to get origin class after including gem using zeitwerk

### ISSUE THREAD

**Issue by crokobit** [fxn/zeitwerk#160]
I am upgrading rails. My project has a custom gem and has a controller inside (with namespace). But if I include the gem I can not get the controller (with same namespace) in the rails main project successfully (which I can get that controller without including the gem). Any idea or clue about this?

Many Thanks. 😭 

Detail:

(In Gem)  https://github.com/crokobit/at-gem-controllers-for-test/
lib/at-gem-controllers/api_v1/base_controller.rb

Setting of zeitwerk in gem: https://github.com/crokobit/at-gem-controllers-for-test/blob/master/lib/at-gem-controllers.rb
```ruby
class Controllers
end

require 'rubygems'
require 'bundler/setup'
Bundler.require(:default)
require 'zeitwerk'

loader = Zeitwerk::Loader.for_gem
loader.inflector.inflect(
  "at-gem-controllers"   => "Controllers",
)
loader.push_dir("#{__dir__}/at-gem-controllers")
loader.setup
```

(In Rails) https://github.com/crokobit/test-zeitwerk

has controller:
app/controllers/api_v1/ping_controller.rb

I found that when I am including the at-gem-controllers gem, I will not get the ApiV1::PingController but I can get the Api::BaseController. however, if I remove the gem, I will get the ApiV1::PingController.

**Comment by fxn** [comment]
Yeah, you need to make sure the namespace is loaded before Zeitwerk's `setup`. Please, have a look at [these docs](https://github.com/fxn/zeitwerk#reopening-third-party-namespaces).

**Comment by crokobit** [comment]
@fxn 
I tried by adding require 'api_v1'. in the gem. But I  got ` cannot load such file -- api_v1 (LoadError)`
I don't have a file like `api_v1.rb`. The namespace is generated by zeitwerk. So maybe it is not like the case of adding `require "active_job"` in the doc.

see. https://github.com/crokobit/at-gem-controllers-for-test/pull/1

**Comment by fxn** [comment]
We need to find the file that defines the module in that gem. Can you `require "api_v1/base_controller"`?

**Comment by crokobit** [comment]
@fxn 
I found that I need to add `require "at-gem-controllers/api_v1/base_controller"` to require the `base_controller.rb`. But after adding that I got 
`
/at-gem-controllers-for-test/lib/at-gem-controllers/api_v1/base_controller.rb:2:in '<main>': uninitialized constant ApiV1 (NameError)
`

see.https://github.com/crokobit/at-gem-controllers-for-test/pull/1/files

**Comment by fxn** [comment]
Because the gem does not have naming right. The file `at-gem-controllers/api_v1/base_controller.rb` should define `Controllers::ApiV1::BaseController` according to the structure and inflector.

**Comment by fxn** [comment]
BTW, in that case `ApiV1` is not a shared namespace, because the gem would define `Controllers:: ApiV1`, which is unrelated. It would be if you collapse the directory.

**Comment by crokobit** [comment]
@fxn 
I checked in rails main project. In `rails c` I can not get `Controllers::ApiV1::BaseController`。 But I can get `ApiV1::BaseController` and `ApiV1`.


However, If I remove 
```ruby
loader.inflector.inflect(
  "at-gem-controllers"   => "Controllers",
)
```
than I will get `wrong constant name At-gem-controllers inferred by Zeitwerk::GemInflector from file (Zeitwerk::NameError)
`

So it think the gem did define ApiV1 and ApiV1::BaseController. But not defined Controllers::ApiV1.

**Comment by fxn** [comment]
Maybe you required the file directly? Please ignore that advice, I did not realize the namespace is actually not shared.

Let me recommend something, eager load the gem:

```ruby
loader.setup
loader.eager_load
```

and make eager loading succeed.

**Comment by crokobit** [comment]
@fxn 
It works in my test project above. 
Then I add `eager_load` to my seven custom gems( which have a dependency with each other some times ) and try to run `rails c` for my main rails project ( which included those gems ). Then I got another uninitialized constant error.  

I will try to reproduce it. But before that, I wanna ask whether there is something I need to know if I add `eager_load` to those gems with dependency? Will that cause some constant overwritten by another gem?

**Comment by fxn** [comment]
`loader.eager_load` only eager loads the files managed by `loader`.

It all works out of the box if different loaders manage different namespaces, which is the common case. You only need to be careful in the documented case of shared namespaces, and this case does not depend on lazy/eager loading, it has to be addressed anyway.

**Comment by crokobit** [comment]
@fxn 
Since `eager_load` is optional. Why after adding `loader.eager_load` then the issue fixed? 
Original I can get the `Api::PingController` in rails project but after adding the gem I failed to get `Api::PingControlle`r but I can get `Api::BaseController`. Why did it happen without `eager_load`?

Jus curious and because there is another issue about zeitwerk ( I guess ) after the previous issue solved so I think I need to gather more infomation as I can at this moment. 

Thank you for your patient. 🙏

**Comment by fxn** [comment]
The gem is incorrect. You need to fix the gem first, and then we'll move from there.

Go to the gem root directory, execute

```
ruby -Ilib -rat-gem-controllers -e1
```

with `loader.eager_load` at the bottom, and look at the errors.

**Comment by fxn** [comment]
Eager loading, BTW, is just a way to make the errors apparent, otherwise the gem is incorrect, and you're not aware of it.

**Comment by fxn** [comment]
That project does not have a `Gemfile`, it does not even run. See?

We cannot work with an example that does not reflect reality, we first need a gem that works and loads correctly, and then we can see how are the real namespaces your applications are working with.

**Comment by crokobit** [comment]
@fxn 
I added Gemfile to https://github.com/crokobit/at-gem-controllers-for-test/ .
then in the gem's root dir, I executed `ruby -Ilib -rat-gem-controllers -e1`. I think there is no error ( no output there )
So for now I think the gem reflects reality, and if I remove the eager load in the gem the issue will appear.

The issue is: 
`
Original I can get the Api::PingController in the Rails project but after adding the gem  (without eager_load ) I failed to get Api::PingController but I can get Api::BaseController ( defined in the gem ). Then after adding the eager_load I can get both Api::PingController and Api::BaseController.
`

**Comment by fxn** [comment]
Perfect!

Does the Rails application define `ApplicationController` as well like the gem does?

**Comment by crokobit** [comment]
@fxn  Yes. And I found that in my real Rails project there is no ApplicationController defined. So I removed the ApplicationController in my test project and tried to reproduce the issue again. The issue is still reproducible.

**Comment by fxn** [comment]
On my phone.

Perfect, better to have ApplicationController in only one place. It can
technically be in two without reloading, but it is simpler that way.

So yes, ApiV1 is a shared namespace, and that needs carre. You need to
ensure the one in the gem is the one that creates the namespace, so that
reloading in Rails does not remove it. Eager loading in the gem is a simple
way to accomplish this.

El ds, 1 maig 2021 a les 18:44 crokobit ***@***.***> va
escriure:

**Comment by fxn** [comment]
I think that in this particular case, perhaps Zeitwerk could be improved.

If the namespace that would correspond to a certain subdirectory exists when Zeitwerk visits the file tree, it considers someone else defined it and descends into the subdirectory right away. I'd like to see if we can do the same when there is an autoload for it set by someone else. In that case, we could trigger the autoload (which can be Zeitwerk's, or just a regular manual `autoload`), and descend.

**Comment by fxn** [comment]
OK, I finally consider this to be a bug. Let me explain.

Documentation says you should load shared namespaces beforehand, and **your application is doing so** by loading the gem. The gem provides the namespace, and as far as client code is concerned, the namespace is there. It does not matter if the constant exists as such, or it only has an autoload defined for it. Zeitwerk supported the first case, but not the second one.

If the gem says all you need to do to function is requiring the top-level file, that should be it. It does not matter whether that's true because it uses Zeitwerk, or because it issues manual `require` calls, or because it issues manual `autoload` calls. The fact is that by requireing the top-level file the namespace is available.

So, I have added support for this use case in https://github.com/fxn/zeitwerk/commit/1862b6feadd564f833dd124834647c2401add310.

So, by now `loader.eager_load` is a workaround, but in the next release you'll be able to delete it.

Thanks!
