### ISSUE TITLE
uninitialized constant PaperTrail::Version (NameError) Did you mean?  PaperTrail::VERSION

### ISSUE THREAD

**Issue by dorianmariefr** [fxn/zeitwerk#161]
Sometimes I get this error but most of the time everything runs fine.

```
/app/app/models/version.rb:1:in `<main>': uninitialized constant PaperTrail::Version (NameError)
Did you mean?  PaperTrail::VERSION
	from /app/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /app/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /app/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /app/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /app/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /app/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'
	from /app/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:409:in `const_get'
	from /app/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:409:in `block (2 levels) in eager_load'
	from /app/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:733:in `block in ls'
	from /app/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:725:in `foreach'
	from /app/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:725:in `ls'
	from /app/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:404:in `block in eager_load'
	from /app/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:393:in `synchronize'
	from /app/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:393:in `eager_load'
	from /app/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:508:in `each'
	from /app/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:508:in `eager_load_all'
```

I have a model doing:

```
class Version < PaperTrail::Version
...
end
```

not sure if a bootsnap issue, a zeitwerk issue or a papertrail issue

**Comment by fxn** [comment]
Where is `PaperTrail::Version` defined?

**Comment by dorianmariefr** [comment]
in `lib/paper_trail/frameworks/active_record/models/paper_trail/version.rb` https://github.com/paper-trail-gem/paper_trail/blob/master/lib/paper_trail/frameworks/active_record/models/paper_trail/version.rb

**Comment by fxn** [comment]
Excellent,

More questions:

* Does it happen in `development` mode?
* Does `bin/rails zeitwerk:check` pass?
* I guess you do not have a deterministic way to reproduce?
* If it is not deterministic but happens often enough to make sense, could you enable autoloading logging in `config/application.rb` (`Rails.autoloaders.log!`), and repeat until you hit the error?

**Comment by dorianmariefr** [comment]
> * Does it happen in `development` mode?

I'm not sure, but I don't remember it happening on development mode

> * Does `bin/rails zeitwerk:check` pass?

```
Hold on, I am eager loading the application.

WARNING: The following directories will only be checked if you configure
them to be eager loaded:

  /Users/dorianmariefr/src/parlement/spec/mailers/previews

You may verify them manually, or add them to config.eager_load_paths
in config/application.rb and run zeitwerk:check again.

Otherwise, all is good!
```

> * I guess you do not have a deterministic way to reproduce?

sadly not

> * If it is not deterministic but happens often enough to make sense, could you enable autoloading logging in `config/application.rb` (`Rails.autoloaders.log!`), and repeat until you hit the error?

actually I realize I don't need this model anymore, thanks for the help anyway

**Comment by fxn** [comment]
I see PaperTrail defines a Rails railtie and does not autoload anything. This smells like a missing `require` call from within the gem.

When you load the gem entrypoint, [this code](https://github.com/paper-trail-gem/paper_trail/blob/49659e8a0c4cb0c80aeab344b7b434de7f057c88/lib/paper_trail.rb#L123-L127) loads stuff conditionally. While the pure-AR branch [requires that file](https://github.com/paper-trail-gem/paper_trail/blob/49659e8a0c4cb0c80aeab344b7b434de7f057c88/lib/paper_trail/frameworks/active_record.rb#L11), the Rails branch does not seem to, if you follow from [here](https://github.com/paper-trail-gem/paper_trail/blob/master/lib/paper_trail/frameworks/rails.rb).

So smells like a missing `require` that sometimes it is not missing because some code path loads the file.

**Comment by fxn** [comment]
```
% ag 'require.*models.*version'
lib/paper_trail/frameworks/active_record.rb
11:require "paper_trail/frameworks/active_record/models/paper_trail/version"
```

Summary 👆.

**Comment by fxn** [comment]
I have deleted the comments with hypothesis before, I tried in a vanilla app and the model is loaded [by the railtie](https://github.com/paper-trail-gem/paper_trail/blob/49659e8a0c4cb0c80aeab344b7b434de7f057c88/lib/paper_trail/frameworks/rails/railtie.rb#L26).
