### ISSUE TITLE
Cannot autoload file under this circumstance 

### ISSUE THREAD

**Issue by rainerborene** [fxn/zeitwerk#162]
Say you've the follow directory structure:
```
app/workers/example/a.rb
lib/example/b.rb
lib/example.rb
```
If you try to access `Example::B` it would not work.

**Comment by fxn** [comment]
Can you give more context? Is `lib` a root directory?

**Comment by rainerborene** [comment]
@fxn Sure. It's a Rails application using `zietwerk` mode. By the way, `lib` autoload is enabled on `config/application.rb` through this line:
```ruby
config.autoload_paths << "#{config.root}/lib"
```

**Comment by fxn** [comment]
Should work out of the box. Do you have a way to reproduce?

**Comment by rainerborene** [comment]
That's weird. Now it's working fine. I think it was related to `bootsnap` cache or something. Thanks for the fast response!

**Comment by fxn** [comment]
Strange, that has routinely worked correctly since the beginning.

What did you do? Remove the cache directory? Reboot Spring?

**Comment by rainerborene** [comment]
I stopped `spring` and run `bundle update`. But `bootsnap` kept the same version as before. If I face this problem again, I'll provide more feedback.

**Comment by fxn** [comment]
Great!

If you can reproduce again ever, autoloader traces would be very valuable. You can enable them throwing

```ruby
Rails.autoloaders.log!
```

in _config/application.rb_, and then sharing the output of

```
bin/rails runner Example::B
```

Thanks!
