### ISSUE TITLE
Add gem namespace automatically

### ISSUE THREAD

**Issue by bkuhlmann** [fxn/zeitwerk#169]
## Overview

Would it be possible to have Zeitwerk ensure the current namespace for a gem is loaded without having to define the namespace manually to reduce a few lines of code within a gem's main file for requirement purposes? I ask because if you forget to define your namespace after running `loader.setup`, downstream dependent gems will throw the following errors:

``` bash
NameError:
  uninitialized constant GitPlus
```

I discovered this issue when upgrading to Zeitwerk. Everything tested positively locally but after releasing the new version to Ruby Gems, I discovered dependant gems would fail due to not defining the gem's main namespace.

## Steps to Recreate

Consider the following entry point for my [Git+](https://www.alchemists.io/projects/git_plus) gem:

``` ruby
# frozen_string_literal: true

require "zeitwerk"

loader = Zeitwerk::Loader.for_gem
loader.setup

# Main namespace.
module GitPlus
end
```

Notice that the last few lines with the empty module *must* be defined or you'll have `NameError` issues when requiring the gem as a dependency in downstream gems.

## Desired Behavior

What I'd like to be able to do is write the implementation this way (notice that defining the `GitPlus` module has been removed in this code snippet):

``` ruby
# frozen_string_literal: true

require "zeitwerk"

loader = Zeitwerk::Loader.for_gem
loader.setup
```

Unfortunately, the above will result in `NameError` issues when requiring the gem as a dependency in downstream gems.

## Environment

- Ruby 3.0.1
- Zeitwerk 2.4.2

**Comment by fxn** [comment]
Let's consider this:

```
% cat lib/foo.rb
require "zeitwerk"

loader = Zeitwerk::Loader.for_gem
loader.setup

% cat lib/foo/x.rb
Foo::X = 1

% ruby -Ilib -rfoo -e 'p Foo::X'
-e:1:in `<main>': uninitialized constant Foo (NameError)
```

This is correct, because `lib/foo.rb` does not define `Foo`, and the existence of `lib/foo.rb` is saying it is an explicit namespace. What I want to understand is, how could your test suite pass?

**Comment by bkuhlmann** [comment]
I think I understanding this better now based on your feedback. So the test suite passes because of my Gemfile which, in turn, loads my gemspec and defines my missing constants which is why this worked locally and on CI but not when used in production with downstream gems. To more clearly illustrate, here's what I discovered based on your feedback:

- Bundler loads my Gemfile which points to my gemspec. Specifically, [this line](https://github.com/bkuhlmann/git_plus/blob/main/Gemfile#L5).
- My gemspec, in turns, loads version information as [required here](https://github.com/bkuhlmann/git_plus/blob/main/git_plus.gemspec#L3). Due to this fact, this is the reason why I confused Zeitwerk with loading all constants properly via local testing and CI builds but then was surprised when downstream gem dependencies failed. If I remove the required version information, I'll get the `NameError` exception as experienced with downstream gems.
- Finally, my RSpec spec helper starts by requiring and loading my implementation. Specifically, this [line](https://github.com/bkuhlmann/git_plus/blob/main/spec/spec_helper.rb#L9). ...but bundler has already loaded everything else by that point.

Based on these learnings, I don't believe this is a bug with Zeitwerk but a misunderstanding on my part. I believe if I structure how my gems are loaded, I can catch this issue sooner before discovering production bugs later due to downstream gems failing to load dependent gems like this one.

Thanks for the feedback on this! I'll close this issue. :bow:
