### ISSUE TITLE
require_relative not reload gems when used with zeitwerk.

### ISSUE THREAD

**Issue by zw963** [fxn/zeitwerk#170]
A example to explain this issue.

Assume we have following code:

1. 
```rb
# this file was managed by zeitwerk.

class App < Roda
  route do |r|
    Dir["routes/**/*.rb"].each do |route_file|
      require_relative "#{__dir__}/../#{route_file}"
    end
  end
end
```

It works as expected when i first time start my app. 

But, after i change require_relative gem path to following, and run `loader.reload`

2.
```rb
Dir["routes/**/*.rb"].each do |route_file|
      require_relative "../#{route_file}"
end
```

It seem like `require_relative "../???"` always return false in this case, it should reload, but it not.
so, the result is, all code in routes/**/*.rb is missing.

This issue can happen if exchange above two sample code, that is, it works on "../#{route_file}",
but not work after change to "#{__dir__}/../#{route_file}".

Thank you.

**Comment by fxn** [comment]
Zeitwerk does not support `require_relative`, see why in [this comment](https://github.com/fxn/zeitwerk/blob/7394a579916dc3526cc61a55aba28618bb3cd7e9/lib/zeitwerk/kernel.rb#L46-L64).

Support for `require` is undocumented because it has some caveats if the file does not define the expected constant, but it is intended to work if all is right. In your case:

```ruby
class App < Roda
  route do |r|
    Dir["routes/**/*.rb"].each do |route_file|
      require File.expand_path(route_file)
    end
  end
end
```

Could you try that?

**Comment by fxn** [comment]
BTW, I am not familiar with Roda, the answer above assumes the route files follow conventions and are managed by Zeitwerk, only you want to eager load them. If that assumption is wrong, then the advice above may not work, please let me know.

**Comment by zw963** [comment]
> Support for `require` is undocumented by now because it has some caveats if the file does not define the expected constant

Yes, the files in `PROJECT_ROOT/routes/`, e.g. `PROJECT_ROOT/routes/posts.rb`, use a form like this:

```rb
class App
  hash_routes.on "posts" do |r|
    "posts"
  end
end
```
because those files in routes/ not follow conventions of zeitwerk, so, i have to try to eager load it use a each loop, for the file where this each loop live in, it managed by zeitwerk, and follow the convention.(it was defined on a file named app.rb),
this issue tested on development mode, that is, use following code.

```
loader.enable_reloading
loader.setup
Listen.to(*folders, wait_for_delay: 1) { loader.reload }.start
``` 

BTW: [following](https://github.com/zw963/marketbet_crawler/blob/test_zeitwerk_issue/app/app.rb#L22-L25) code still not work as expected when i change to use require instead of require_relative, the issue is.

1. start server use following code:
```rb
Dir["routes/**/*.rb"].each do |route_file|
      require File.expand_path(route_file)
    end
```

2. comment `require ....` in above code, it works, those code in routes/ not available now.

3. uncomment those code again, it not work, those code in routes/ still not available.

Thank you.

**Comment by zw963** [comment]
BTW: my zeitwerk config is [here](https://github.com/zw963/marketbet_crawler/blob/test_zeitwerk_issue/config/hot_reloader.rb), and for the hot_reloader gem used in this file, please check [here](https://github.com/zw963/hot_reloader/blob/master/lib/hot_reloader.rb)

**Comment by fxn** [comment]
I see!

So, the problem is that `require` is idempotent for files not loaded by Zeitwerk. That is, if you

```ruby
require "nokogiri"
```

in `app/app.rb`, no matter how many times you reload, that line will load `nokogiri.rb` only once.

In your application, when a reload happens `App` is a new class, but the `require`-like lines are idempotent, so don't load the routes again.

In a case like this, you want the files to be interpreted every time the class is defined, you need something that is not idempotent, and that is `Kernel#load`:

```ruby
class App < Roda
  route do |r|
    Dir["routes/**/*.rb"].each do |route_file|
      load File.expand_path(route_file)
    end
  end
end
```

Could you please try that?

**Comment by fxn** [comment]
Are you sure that loop needs to run inside a `route` block? Seems suspicious at first sight, maybe this simplification

```ruby
class App < Roda
  Dir["routes/**/*.rb"].each do |route_file|
    load File.expand_path(route_file)
  end
end
```

is more better?

**Comment by zw963** [comment]
> In a case like this, you want the files to be interpreted every time the class is defined, you need something that is not idempotent, and that is `Kernel#load`:

Thank you very much, change to use load instead of require, it works!



> Are you sure that loop needs to run inside a `route` block? Seems suspicious at first sight, maybe this simplification

Yes, roda use some different tech, as describe in [mastering-roda](https://fiachetti.gitlab.io/mastering-roda/#basic-routing)

```
This demonstrates one of the core principles of Roda's design. In many web frameworks, the routing definitions are executed when the program starts, and compiled into some kind of internal data structure. Roda is different, in that the route block is executed every time a request is received.
```

so, we must reevaluate all route code when request is coming, if fact, move loop out of route block is works too.
i guess we should do like this when on production, because we define all routes within App namespace, it works,
but, if done like this, when in development, for make new changed code take effect immediately instead of have to
change app.rb to let zeitwerk make new route take effect,  former is more better.

Help a more question:

if we use with load, even eager load on production, load will always evaluate all the codes in `routes/` every each request, instead on once, right?

**Comment by fxn** [comment]
You want route definitions to be executed again when routes change! Not on every request, not even on development.

As I understand it, the code should be

```ruby
class App < Roda
  Dir["routes/**/*.rb"].each do |route_file|
    load route_file
  end
end
```

Then, ideally, in `development` mode you configure `listen` to watch the route files in addition to the application files, and trigger a reload if any of them changes.

**Comment by zw963** [comment]
> Then, ideally, in `development` mode you configure `listen` to watch the route files in addition to the application files, and trigger a reload if any of them changes.

Thank you very much, it works as expected after i add routes into zeitwerk pushdir, and listen to it.

```rb
loader = Zeitwerk::Loader.new
loader.push_dir("#{__dir__}/../routes")
loader.enable_reloading
      loader.setup
```

Then add this loop into App class instead of in route block.

```rb
class App < Roda
  Dir["routes/**/*.rb"].each do |route_file|
    load route_file
  end
end
```

I guess i misunderstood somethings before, because i thought the ruby files in `routes/**/*.rb` not follow the constant name convention, so, i guess it is not loadable, but i am wrong admittedly.

I am reading [reloading](https://github.com/fxn/zeitwerk#reloading) section in README several times, i think i know why this works now.

i thought zeitwerk set up a `Module#autoload` for each one of the constants that are inferred by the name of the files inside routes, but, because we load all files in `routes` already manually in the loop, so, those Module#autoload was ignored, not to try find a expected constants in this case, because i enable  `loader.enable_reloading` for this `routes`, so autoload still works, am i right?

anyway, i want to say, this feature is not so easy to understand and not so obviously after use 2 years zeitwerk for me.
in fact, i never use like this before.

Thank you.

**Comment by fxn** [comment]
No, no. You do not have to add that directory to Zeitwerk. Let me explain.

If you do

```ruby
loader.push_dir("#{__dir__}/../routes")
```

then Zeitwerk expects `app/routes/blog.rb` to define `Blog`, and will set an autoload on `Object` to load that file when `Blog` is first used. Zeitwerk is lazy, so you don't see the problem because the application does not mention `Blog`, but if you eager load, you'll see the error.

That file does not define `Blog`, and therefore should not be managed by Zeitwerk. Route files are splitting the definition of `App`, just that. You could delete them and put eveything within the class body of `App` in `app/app.rb`, right?

You need to undo that configuration.

If you want to split the implementation of `App` in different files, then you need to work a bit more. You need to monitor if the route files change. Not add them to Zeitwerk, just monitor if they change. You could even do that without `listen`, on every request in dev mode, check their mtime, if it changed, reload the application. See what I mean?

**Comment by zw963** [comment]
Okay, let me explain one by one.

> . You could delete them and put eveything within the class body of App in app/app.rb, right?

Yes, you are right. 

even, this project just a study project, for learn Roda. Roda have a very small core, almost everything is implement use plugin, i am trying a plugin named [hash_routes](https://github.com/jeremyevans/roda#hash_routes-plugin-), i guess i have to write code like this if i want use this plugin to split routes 
to separate small files.



> Zeitwerk is lazy, so you don't see the problem because the application does not mention `Blog`, but if you eager load, you'll see the error.

Yes, i saw it.

> You could even do that without listen, on every request in dev mode, check their mtime, if it changed, reload the application. See what I mean?

Yes, i see, but, the issue is, how to reload it? 

Thank you.

**Comment by zw963** [comment]
BTW: 

after move Dir loop into route block, auto reload is working, even, not add routes/* into root directories.

but, one more question is, add this loop into route block (will will be reevaluate each time a request is coming),
if there exists a significant performance penalty? compare to outer.

Thank you.

**Comment by zw963** [comment]
> Well, you are reloading somehow, no? Zeitwerk does not reload by itself, the parent application has to call the `reload` method explicitly.
> 
> So, if you check mtimes and they differ from previous request, you just grab the loader and execute `loader.reload`.

Ummm, let me confirm again, so, i guess what you means is,

1. we don't need add routes/ into root directories, so, zeitwerk not monitor routes/ folder i thought.
2. we need listen routes/**/*.rb changes, if it was, we can still run zeitwerk's reload methods to apply the newest changes from routes/

more explain, even loader's root directories is empty, we can still use loader.reload to make new code take effect, right?

If i guess right, i test this thought use following code:

loader = Zeitwerk::Loader.new
folders = what_ever_need_add_to_root_directory
loader.push_dir(folders)
loader.enable_reloading
reloadable_folders = ["#{__dir__}/../routes"]

Listen.to(*(folders + reloadable_folders)) { loader.reload }.start

It not work, after i changed file in routes/, code unloaded, but not reload.

following is the logs:

D, [2021-07-14T10:41:59.140243 #61593] DEBUG -- : listen: final changes: {:modified=>["/home/zw963/Stocks/marketbet_crawler/routes/blog.rb"], :added=>[], :removed=>[]}
D, [2021-07-14T10:41:59.140321 #61593] DEBUG -- : Zeitwerk@b5917f: autoload for InsiderParser removed
D, [2021-07-14T10:41:59.140355 #61593] DEBUG -- : Zeitwerk@b5917f: autoload for InstitutionParser removed
D, [2021-07-14T10:41:59.140375 #61593] DEBUG -- : Zeitwerk@b5917f: autoload for Exchange removed
D, [2021-07-14T10:41:59.140391 #61593] DEBUG -- : Zeitwerk@b5917f: autoload for Insider removed
D, [2021-07-14T10:41:59.140405 #61593] DEBUG -- : Zeitwerk@b5917f: autoload for Institution removed
D, [2021-07-14T10:41:59.140419 #61593] DEBUG -- : Zeitwerk@b5917f: autoload for Stock removed
D, [2021-07-14T10:41:59.140433 #61593] DEBUG -- : Zeitwerk@b5917f: autoload for Task removed
D, [2021-07-14T10:41:59.140454 #61593] DEBUG -- : Zeitwerk@b5917f: App unloaded
D, [2021-07-14T10:41:59.141082 #61593] DEBUG -- : Zeitwerk@b5917f: autoload set for InsiderParser, to be loaded from /home/zw963/Stocks/marketbet_crawler/app/parsers/insider_parser.rb
D, [2021-07-14T10:41:59.143695 #61593] DEBUG -- : Zeitwerk@b5917f: autoload set for InstitutionParser, to be loaded from /home/zw963/Stocks/marketbet_crawler/app/parsers/institution_parser.rb
D, [2021-07-14T10:41:59.143794 #61593] DEBUG -- : Zeitwerk@b5917f: autoload set for App, to be loaded from /home/zw963/Stocks/marketbet_crawler/app/app.rb
D, [2021-07-14T10:41:59.143872 #61593] DEBUG -- : Zeitwerk@b5917f: autoload set for Exchange, to be loaded from /home/zw963/Stocks/marketbet_crawler/app/models/exchange.rb
D, [2021-07-14T10:41:59.143922 #61593] DEBUG -- : Zeitwerk@b5917f: autoload set for Insider, to be loaded from /home/zw963/Stocks/marketbet_crawler/app/models/insider.rb
D, [2021-07-14T10:41:59.143967 #61593] DEBUG -- : Zeitwerk@b5917f: autoload set for Institution, to be loaded from /home/zw963/Stocks/marketbet_crawler/app/models/institution.rb
D, [2021-07-14T10:41:59.144013 #61593] DEBUG -- : Zeitwerk@b5917f: autoload set for Stock, to be loaded from /home/zw963/Stocks/marketbet_crawler/app/models/stock.rb
D, [2021-07-14T10:41:59.144056 #61593] DEBUG -- : Zeitwerk@b5917f: autoload set for Task, to be loaded from /home/zw963/Stocks/marketbet_crawler/app/models/task.rb

Thank you.

**Comment by zw963** [comment]
Oh, sorry for confusing, it is not work because i change `load "???"` to `require "???"` at some time ...

It works, i will write some test for confirm this work, and add this feature to hot_reloader gem.
