### ISSUE TITLE
Add a log item which indicate current start as eagerloading mode.

### ISSUE THREAD

**Issue by zw963** [fxn/zeitwerk#171]
I notice, when i use zeitwerk, and enable logs, whatever if run `loader.eager_load` to enable eagerloading, there is no clue to know if current application is started with eagerloading or not.

so, do you consider add a log item to indicate current loader start as `loader.eager_load` ? 

Thank you.

**Comment by fxn** [comment]
Good suggestion, I've implemented it thanks.

This will be out with 2.5. I'll release that version when the removal of `classic` mode in `rails/main` is done.

**Comment by zw963** [comment]
I saw the eager load log now, thank you.
