### ISSUE TITLE
 ENV.delete['a_env_variable']  return nil after reload

### ISSUE THREAD

**Issue by zw963** [fxn/zeitwerk#174]
E.g. following is a example

```rb
# app/app.rb
class App < Roda
  plugin :sessions, secret: ENV.delete['APP_SESSION_SECRET']
end
```
Above app is working when start as web server, because ENV.delete return expected string first time. 

but when app/app.rb was modified, class `App` get reloaded. then `ENV.delete['APP_SESSION_SECRET']` 
will return nil this time instead of string.

I don't know if this is a issue, anyway, mention here, for discuss and avoid pitfall.

**Comment by fxn** [comment]
As it is written, that is expected.

Why does the code delete instead of just read?

```ruby
class App < Roda
  plugin :sessions, secret: ENV['APP_SESSION_SECRET']
end
```

**Comment by zw963** [comment]
> As it is written, that is expected.
> 
> Why does the code delete instead of just read?
> 
> ```ruby
> class App < Roda
>   plugin :sessions, secret: ENV['APP_SESSION_SECRET']
> end
> ```

For security reason? anyway, i see some code perfer write like this. after use it first time, then fetch it again, get nil.

**Comment by casperisfine** [comment]
@zw963 Zeitwerk is a code reloader, so by definition any code loaded by Zeitwerk is susceptible to be ran more than once, so any side effect in autoloaded code is susceptible to break.

If you really want to mutate the ENV for security purposes, you can check if Zeitwerk is in eagerload mode or not.

**Comment by zw963** [comment]
> so by definition any code loaded by Zeitwerk is susceptible to be ran more than once, so any side effect in autoloaded code is susceptible to break.

Yes, i understood it,  i guess what you means is `idempotent`, when do reload, all code must be `idempotent`.



> you can check if Zeitwerk is in eagerload mode or not.

I am wonder,  how to do that?

**Comment by casperisfine** [comment]
> all code must be `idempotent`.

That's one way to put it yes.

> I am wonder, how to do that?

Not sure how Roda expose the Zeitwerk loader. But for Rails: `if Rails.autoloaders.main.eager_load`. I suppose Roda expose the instance somewhere?

**Comment by fxn** [comment]
Do you have a place at boot time that is not reloaded? Because if that was the case, you could do

```ruby
APP_SESSION_SECRET = ENV.delete('APP_SESSION_SECRET')
```

and then 

```ruby
class App < Roda
  plugin :sessions, secret: APP_SESSION_SECRET
end
```

The trick here is to store the value in a place that is not subject to reloads.

**Comment by zw963** [comment]
> Not sure how Roda expose the Zeitwerk loader. But for Rails: `if Rails.autoloaders.main.eager_load`

I guess `loader.eager_load` is let zeitwerk loader to do eager load, not check if current was eager load.




> Do you have a place at boot time that is not reloaded? Because if that was the case, you could do
> APP_SESSION_SECRET = ENV.delete('APP_SESSION_SECRET')

Sure, there is, but, if do like that, it does't make sense to use `ENV.delete`, because we can get secret more
easily then before use a constant  : )

anyway, thanks all,  this is another pitfall relative to `idempotent`, maybe it be worth to mention in README
for `require` and `ENV.delete` ?

**Comment by casperisfine** [comment]
> I guess `loader.eager_load` is let zeitwerk loader to do eager load, not check if current was eager load.

My bad. I was answering from memory, and somehow I remembered it as an attr_accessor on a boolean. Sorry about the bad info. SO yeah, I guess you'll have to check some Roda config. Again I know little of Roda, so can't help here.

**Comment by fxn** [comment]
When you reload, code is executed again. I believe we do not need to mention that in the README, that is a given!

For example, if you have

```ruby
class C
  @t = Time.now
end
```

it goes without saying that every time you reload, the value of `@t` is different. Not only it is different `@t` is an ivar of a totally new object, the previous `C` is gone.

I think we can close this one.
