### ISSUE TITLE
require_dependency with Rails Engines

### ISSUE THREAD

**Issue by olbrich** [fxn/zeitwerk#175]
In [this announcement](https://weblog.rubyonrails.org/2019/2/22/zeitwerk-integration-in-rails-6-beta-2/) there include a line that 'All known use cases of require_dependency have been eliminated.'

In the [Rails Guide for Engines](https://guides.rubyonrails.org/engines.html#app-directory) there is an explicit recommendation to use `require_dependency` to deal with certain scenarios.

Is the guide out of date?
Is there any guidance about how to use zeitwerk with Rails engines?

**Comment by fxn** [comment]
Yes, it is out of date. If the parent application is in `zeitwerk` mode, you no longer need that `require_dependency`.

> Is there any guidance about how to use zeitwerk with Rails engines?

There's not much to say, but I'll add some docs about it.

`require_dependency` is still available to ease the transition, and the predicate `Rails.autoloaders.zeitwerk_enabled?` was implemented having engines in mind (but use cases are rare).

In the case above, if you only need to support `zeitwerk` mode, you can just delete the `require_dependency`. If need to work in both modes, you can leave it.

**Comment by fxn** [comment]
Addressed in https://github.com/rails/rails/commit/549db9cc1963d18df63459b93c4db624b2270460.

Please, do not hesitate to ask further questions.

**Comment by olbrich** [comment]
Thanks!
