### ISSUE TITLE
Only reload updated file instead of all files where class is opened

### ISSUE THREAD

**Issue by HoneyryderChuck** [fxn/zeitwerk#177]
Hi, I'm coming from this [other issue](https://github.com/jeremyevans/roda-sequel-stack/issues/21), where a limitation of zeitwerk on classes opened multiple times was identified. I wonder whether there's a workaround for this, given how popular `roda` multi_route plugin is in the community, and how I'd rather use `zeitwerk` rather than `unreloader` to reload my code in between requests. Not a big concern for small applications though, which I expect most `roda` apps in the wild to be, but still good to know if it's possible.

**Comment by fxn** [comment]
Yeah... we cannot do partial reloads. I replied in the original issue.
