### ISSUE TITLE
Conflicting Path Race Condition with Multiple Loaders

### ISSUE THREAD

**Issue by mvastola** [fxn/zeitwerk#179]
Hi,
So I'm running into an annoying issue that I think is due to a bug.. I have a directory structure resembling this:
```
dir/
├── bar.rb
├── foo.rb
└── subdir/
    └── baz.rb
```

.. where `dir` and `subdir` are directories, with `subdir` inside `dir` (as you might have guessed). 

I need to handle them slightly differently, so I was attempting to approach this via two distinct zeitwerk loaders: 
- one for `subdir` (which usually gets loaded first, though that's not a hard and fast rule)
- one for its parent dir, `dir`, with an ignore path of `subdir` so as to prevent conflicts

From the code, this definitely seems to be a supported use case, but I'm running into problems in `Zeitwerk::Loader::Config#manages?`, which is invoked by `Zeitwerk::Loader#raise_if_conflicting_directory`.

Namely, due to the way [`#manages?`](https://github.com/fxn/zeitwerk/blob/fbcb3e042e7042d3d1de1296b3f11ce5428d5277/lib/zeitwerk/loader/config.rb#L252-L254) is implemented. 

Let's say we have two loaders: `loader1` and `loader2`, and `subdir` is already pushed to `loader1`.

When I try to add `dir` to `loader2`, the current algorithm ends up checking if `loader1` has `dir` (or an ancestor) as an ignored path, even though that's not necessary since `loader2` has an ignore path of `subdir`.

If it's helpful, I made a gist demonstrating this issue: https://git.io/JEQiP

**Comment by fxn** [comment]
Excellent bug report.

It is fixed in https://github.com/fxn/zeitwerk/commit/015e6328e20036d277cec4f0bfb9e1303661bed2. Version `2.5.0.beta3` is up with this fix.

**Comment by mvastola** [comment]
@fxn Thanks!!
