### ISSUE TITLE
Simple inner constant & UPPER_CASE

### ISSUE THREAD

**Issue by qortex** [fxn/zeitwerk#184]
I try to define a simple inner constant as in the docs:
```ruby
# authorization/lands_constitutions.rb
Authorization::LANDS_CONSTITUTIONS = {
  # ...
}.freeze
```

I get:

```ruby
NameError (uninitialized constant Authorization::LANDS_CONSTITUTIONS)
Did you mean?  Authorization::LandsConstitutions
```

And indeed:
```
Zeitwerk@5dc0ab: autoload set for Authorization::LandsConstitutions, to be loaded from /home/.../product/backend/libs/authorization/lands_constitutions.rb
```

Asking for `Authorization::LandsConstitutions` (I'm in irb with `rack-console` on a custom Roda app) then triggers the load for `lands_constitutions.rb` and thus:
```
Zeitwerk::NameError (expected file /home/.../product/backend/libs/authorization/lands_constitutions.rb to define constant Authorization::LandsConstitutions, but didn't)
```

After that, asking for `Authorization::LANDS_CONSTITUTIONS` works well, because the file was loaded as part of the previous request.

Is it expected behaviour, or is there something in my setup that triggers this?

**Comment by casperisfine** [comment]
Yes, it is the default behavior, you might want to read on the inflection mecanism: https://github.com/fxn/zeitwerk#inflection

In short Zeitwerk sees `lands_constitutions.rb`, so it does more or less `"lands_constitutions".camelize` and expects `LandsConstitutions`.

So you either want to define that constant inside `authorization.rb` or to tell Zeitwerk that this specific file need to be handled differently.

**Comment by fxn** [comment]
Hey! Yes, this agrees with the documentation indeed.

A file called `lands_constitutions.rb` is expected _by default_ to define `LandsConstitutions`, which is different from `LANDS_CONSTITUTIONS`.

Your use case is supported, you have two options:

### Option 1

You can define the constant directly in `authorization.rb`:

```ruby
module Authorization
  LANDS_CONSTITUTIONS = { ... }.freeze
end
```

### Option 2

If you prefer a dedicated file, you need to tell the inflector that the file defines a constant with a custom name. Execute this before the call to `setup`:

```ruby
loader.inflector.inflect("lands_constitutions" => "LANDS_CONSTITUTIONS")
```

You can read more about this [in this section of the docs](https://github.com/fxn/zeitwerk#inflection).

**Comment by fxn** [comment]
And now I see @casperisfine's reply, which was perfect.

**Comment by qortex** [comment]
Thanks for the quick answer!

Option 2 works perfectly thanks!
Though I can't get Option 1 to work. I don't really understand why (but it's not really an option in my setting anyway for convention purposes).

I was basing my code on the examples found here, where `MAX_RETRIES` is my `LANDS_CONSTITUTIONS`: https://github.com/fxn/zeitwerk#inner-simple-constants. Maybe it would be interesting to have more examples that explore the cases we discuss here? My understanding is that the example:
```ruby
# http_crawler/max_retries.rb
HttpCrawler::MAX_RETRIES = 10
```
isn't correct, or I am missing something?

**Comment by fxn** [comment]
@qortex That's a good point. Indeed, the example could be interpreted as you did. I have clarified this point in https://github.com/fxn/zeitwerk/commit/5d1b089e40451279e7a25a9198df95f606007c57.

Thanks!
