### ISSUE TITLE
2.5.0 update causes new autoloading bug with #hash method.

### ISSUE THREAD

**Issue by ethn** [fxn/zeitwerk#188]
I'm afraid I don't have time to generate a test, but the short version is that the call `include Card::Env::Location` triggers the autoloading of card/env.rb, which contains the method:

```
      def hash hashish
        case hashish
        when Hash then hashish.clone
        when ActionController::Parameters then hashish.to_unsafe_h
        else {}
        end
      end
```
full file [here](https://github.com/decko-commons/decko/blob/main/card/lib/card/env.rb)

After the 2.5.0 update, this generates the following new error:

`ArgumentError: wrong number of arguments (given 0, expected 1)`
backtrace:

```
/Users/ethan/dev/decko/gem/card/lib/card/env.rb:48:in `hash'
/Users/ethan/.gem/ruby/2.7.3/gems/zeitwerk-2.5.0/lib/zeitwerk/autoloads.rb:56:in `hash'
/Users/ethan/.gem/ruby/2.7.3/gems/zeitwerk-2.5.0/lib/zeitwerk/autoloads.rb:56:in `delete'
/Users/ethan/.gem/ruby/2.7.3/gems/zeitwerk-2.5.0/lib/zeitwerk/autoloads.rb:56:in `delete'
/Users/ethan/.gem/ruby/2.7.3/gems/zeitwerk-2.5.0/lib/zeitwerk/loader/callbacks.rb:11:in `on_file_autoloaded'
/Users/ethan/.gem/ruby/2.7.3/gems/zeitwerk-2.5.0/lib/zeitwerk/kernel.rb:28:in `block in require'
/Users/ethan/.gem/ruby/2.7.3/gems/zeitwerk-2.5.0/lib/zeitwerk/kernel.rb:27:in `tap'
/Users/ethan/.gem/ruby/2.7.3/gems/zeitwerk-2.5.0/lib/zeitwerk/kernel.rb:27:in `require'
/Users/ethan/dev/decko/gem/card/lib/card/format.rb:20:in `<class:Format>'
```

**Comment by fxn** [comment]
Interesting, there's new code that assumes classes and modules that act as namespaces are hashable. But yours shows that assumption cannot be made.

Thanks for giving 2.5.0 a try so quickly, I'll think about it and will come back.

**Comment by ethn** [comment]
Wow, fantastic. Thanks for the quick fix!
