### ISSUE TITLE
How to preload all directory files in 2.5.0 ?

### ISSUE THREAD

**Issue by jonian** [fxn/zeitwerk#189]
Hi, version 2.5.0 removed the `preload` method and the change log has examples for alternatives when preloading a single file or a namespace, but it does not have an example for preloading all files in a directory without namespace.

```
app/settings
  - application_settings.rb
  - orders_settings.rb
  - mailer_settings.rb
```

Before 2.5.0, I was using:

```ruby
Rails.autoloaders.main.preload('app/settings')
```

What is the recommended way to preload all files in the example above?

**Comment by fxn** [comment]
@jonian That is a good use case.

One way to do it that follows the load-using-constants-instead-of-files interface I am pursuing is:

```ruby
Rails.application.config.to_prepare do
  Object.constants(false).each do |cname|
    Object.const_get(cname) if cname.end_with?("Settings")
  end
end
```

I need to document it, but in this particular case you can do it with `require` as well:

```ruby
Rails.application.config.to_prepare do
  Dir.glob("#{Rails.root}/app/settings/*.rb") do |settings|
    require settings
  end
end
```

Both solutions work well with reloading.
