### ISSUE TITLE
Question: Autoloading in Rails 7

### ISSUE THREAD

**Issue by olimart** [fxn/zeitwerk#192]
In `app/lib/csv_analyzer.rb` my class is declared as `class CSVAnalyzer < ActiveStorage::Analyzer`

In Rails 7 it is raising `NameError: uninitialized constant CSVAnalyzer`

This solves the issue however, I don't think this is the right approach since `app/lib` is automatically loaded.
```
# config/application.rb
require_relative "../app/lib/csv_analyzer"
```

I've tried to inflect file name but no success.
```
# config/initializers/inflections.rb
ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect("csv_analyzer" => "CSVAnalyzer")
end
```

Please advise and thanks for your great work.

**Comment by fxn** [comment]
Hi!

> This solves the issue however, I don't think this is the right approach since app/lib is automatically loaded.

Exactly right. You'd issue a `require` if the file was under `lib`. But for autoloadable code in `app/lib` you don't.

> I've tried to inflect file name but no success.

Your approach is correct, configure inflections. In this case, you need to tell AS that "CSV" is an acronym:

```ruby
# config/initializers/inflections.rb
ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.acronym "CSV"
end
```

**Comment by olimart** [comment]
OK, thanks a lot.
