### ISSUE TITLE
The correct way to open a ruby builtin class?

### ISSUE THREAD

**Issue by zw963** [fxn/zeitwerk#195]
Following is a sample:

```rb
# lib/core_ext/time.rb

class Time
  def is_today?
    beginning_of_today = Date.today.to_time
    beginning_of_tomorrow = (Date.today + 1).to_time

    if (beginning_of_today...beginning_of_tomorrow).cover?(self)
      true
    else
      false
    end
  end
end
```

Then try to load it use zeitwerk.

```rb
loader = Zeitwerk::Loader.new
loader.push_dir("#{APP_ROOT}/lib/core_ext")
# do setup
```

Sure, above code not work.

After read [#reopening-third-party-namespaces,](https://github.com/fxn/zeitwerk#reopening-third-party-namespaces), still could not understand what is the correct way to do this, i know this is not a (expected) new class defined by current project, so, just curious,
how to handle this case and why. 

Thank you.

**Comment by fxn** [comment]
Hey! On my phone.

That's a use case for `ignore`. Could you have a look at its documentation
and see if it helps?

El dc, 17 nov 2021 a les 19:40 Billy.Zheng ***@***.***> va
escriure:

**Comment by fxn** [comment]
First use case in [this section](https://github.com/fxn/zeitwerk#ignoring-parts-of-the-project) of the docs.

**Comment by zw963** [comment]
Got it, thanks!
