### ISSUE TITLE
Changelog missing for v2.5.2

### ISSUE THREAD

**Issue by ShockwaveNN** [fxn/zeitwerk#199]
Hi, thanks for your work

Just wondering - is there were any significant changes for v2.5.2?
I've got `dependabot` update but CHANGELOG.md ended on v2.5.1

**Comment by ShockwaveNN** [comment]
Oh, seems something is lost

There is commit - https://github.com/fxn/zeitwerk/commit/9d980151efbdcbcb040911734f8bbba14aa8fae7

But it's not on any `main` branch

**Comment by 3clypse** [comment]
@ShockwaveNN 

I found them here:
- https://github.com/fxn/zeitwerk/blob/1ff6336d937514c923f2c5a60cfaa501f150a7b5/CHANGELOG.md#252-27-december-2021

Also you can check the changes here: https://github.com/fxn/zeitwerk/compare/v2.5.1...v2.5.2

**Comment by ShockwaveNN** [comment]
> Also you can check the changes here: v2.5.1...v2.5.2

Yeah, I agree but should `main` branch include this changes?

**Comment by fxn** [comment]
Oh, it seems I did not push it. Thanks!

**Comment by ShockwaveNN** [comment]
@fxn Thanks for quick reply
