### ISSUE TITLE
Support emoji prefixes in class names

### ISSUE THREAD

**Issue by inem** [fxn/zeitwerk#204]
I created a class named "📦Cache", and put it into file named "📦cache.rb", and got the following error: 

```
wrong constant name 📦cache inferred by Module from file (Zeitwerk::NameError)
```

I understand that it is the expected behavior. The question is wouldn't it make sense to modify this behavior, and for situations when class name starts from emoji(s), then inferred class name would have capitalized first real letter but not emoji? 

I.e.: `📦cache.rb` → `📦Cache` class, and not `📦cache`. 

Emojis are not very capitalizeable as far as I understand.

P.S. I know it all looks really weird, but I do have a real scenario where it would be useful.

**Comment by casperisfine** [comment]
> I.e.: `📦cache.rb` → `📦Cache` class, and not `📦cache`.

Isn't the issue that your file should be named `📦_cache.rb` ? Zeitwerk infer class name from file name.

**Comment by inem** [comment]
Hmm, haven't thought of this! But unfortunately it didn't work either: 

![image](https://user-images.githubusercontent.com/9665/149158687-2c258020-8f1c-4946-b7a0-098d0a9d9b50.png)

**Comment by casperisfine** [comment]
Weird, that should work, I'll try to repro.

**Comment by casperisfine** [comment]
Ok, so I have bad news for you, this isn't a Zeitwerk issue, but a Ruby one:

```ruby
>> Object.const_defined?("📦Cache")
(irb):1:in `const_defined?': wrong constant name 📦Cache (NameError)
```

Since `class 📦Cache; end` is valid syntax, `const_defined?` and friends should also accept that.

I'll file an issue upstream.

**Comment by casperisfine** [comment]
Actually nevermind... It's just not a valid const name at all 🤦 

```
$ ruby /tmp/foo.rb
/tmp/foo.rb:1: class/module name must be CONSTANT
class 📦Cache
```

So yeah, I think you can close, Ruby constants can't start with an emoji.

**Comment by fxn** [comment]
This was indeed something I wondered when writing the lib in the early days. Should Zeitwerk validate file names?

I suspected it could enter too-clever territory, and that Ruby evolves. Better use the constants API and let Ruby decide what it supports.

BTW, that `Module` is puzzling, the message includes `inflector.class`, but that makes sense only for inflectors that are instances of classes in the ordinary sense. I'll see if the error message can be improved.
