### ISSUE TITLE
Fix ignored files from being loaded in dependent gem

### ISSUE THREAD

**Issue by bkuhlmann** [fxn/zeitwerk#205]
## Overview

Hello. :wave: I've run into a situation which seems to break what is documented in the [Test Files Use Case](https://github.com/fxn/zeitwerk#use-case-test-files-mixed-with-implementation-files) example. I think this might be a bug because I can't seem to resolve the conflict.

## Screenshots

![2022-01-12_17-05-30-iTerm2](https://user-images.githubusercontent.com/50245/149242445-ef2a863e-b196-4080-b914-bb6a5772327e.png)

## Steps to Recreate

I'm afraid I don't know of an easy way to reproduce this in an isolated way but hoping this context will be helpful:

1. I'm working on the Git+ gem where I package a [lib/spec](https://github.com/bkuhlmann/git_plus/tree/main/lib/git_plus/spec) folder for downstream dependencies to use with RSpec.
2. Initially, I made the mistake of letting Zeitwerk [load everything in my lib](https://github.com/bkuhlmann/git_plus/blob/main/lib/git_plus.rb) folder but have now corrected that mistake by *explicitly ignoring* the `lib/spec` folder. Here's the code I'm currently using:

``` ruby
# frozen_string_literal: true

require "zeitwerk"

Zeitwerk::Loader.new.then do |loader|
  loader.ignore "#{__dir__}/spec/**/*.rb"
  loader.push_dir __dir__
  loader.setup
end

# Main namespace.
module GitPlus
end
```

Sadily, the problem hasn't gone away. I see the following stack dump on Circle CI when running a Rails build with the Git+ dependency loaded even though Zeitwerk *should* be ignoring the `lib/spec` folder.

<details>
  <summary>Stack Dump</summary>

``` 
/home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:24: warning: method redefined; discarding old require
/home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:27: warning: previous definition of require was here
/home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/rspec_api_documentation-6.1.0/lib/rspec_api_documentation/configuration.rb:163: warning: `&' interpreted as argument prefix
/home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/devise-4.8.1/lib/devise/failure_app.rb:29: warning: method redefined; discarding old default_url_options
/home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/actionpack-6.1.4.4/lib/action_dispatch/routing/url_for.rb:95: warning: previous definition of default_url_options was here

An error occurred while loading ./spec/acceptance/administrative_configurations_spec.rb.
Failure/Error: require File.expand_path("../config/environment", __dir__)

Zeitwerk::NameError:
  expected file /home/circleci/repo/vendor/bundle/ruby/3.1.0/bundler/gems/git_plus-ab1d7923f13f/lib/git_plus/spec/shared_contexts/git_commit.rb to define constant GitPlus::Spec::SharedContexts::GitCommit, but didn't

        raise Zeitwerk::NameError.new("expected file #{file} to define constant #{cpath}, but didn't", cref.last)
        ^^^^^
# ./vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/loader/callbacks.rb:25:in `on_file_autoloaded'
# ./vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:28:in `require'
# ./vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/loader/helpers.rb:95:in `const_get'
# ./vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/loader/helpers.rb:95:in `cget'
# ./vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/loader.rb:231:in `block (2 levels) in eager_load'
# ./vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
# ./vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/loader/helpers.rb:18:in `each_child'
# ./vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/loader/helpers.rb:18:in `ls'
# ./vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/loader.rb:226:in `block in eager_load'
# ./vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/loader.rb:211:in `synchronize'
# ./vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/loader.rb:211:in `eager_load'
# ./vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/loader.rb:311:in `each'
# ./vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/loader.rb:311:in `eager_load_all'
# ./vendor/bundle/ruby/3.1.0/gems/railties-6.1.4.4/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
# ./vendor/bundle/ruby/3.1.0/gems/railties-6.1.4.4/lib/rails/initializable.rb:32:in `instance_exec'
# ./vendor/bundle/ruby/3.1.0/gems/railties-6.1.4.4/lib/rails/initializable.rb:32:in `run'
# ./vendor/bundle/ruby/3.1.0/gems/railties-6.1.4.4/lib/rails/initializable.rb:61:in `block in run_initializers'
# ./vendor/bundle/ruby/3.1.0/gems/railties-6.1.4.4/lib/rails/initializable.rb:60:in `run_initializers'
# ./vendor/bundle/ruby/3.1.0/gems/railties-6.1.4.4/lib/rails/application.rb:391:in `initialize!'
# ./config/environment.rb:2:in `<top (required)>'
# ./spec/rails_helper.rb:6:in `require'
# ./spec/rails_helper.rb:6:in `<top (required)>'
# ./spec/acceptance/administrative_configurations_spec.rb:1:in `require'
# ./spec/acceptance/administrative_configurations_spec.rb:1:in `<top (required)>'

An error occurred while loading ./spec/acceptance/android_version_spec.rb.
Failure/Error: require File.expand_path("../config/environment", __dir__)
```
</details>

I've not seen this issue crop up with normal Ruby project which depend upon Git+. This only happens in Rails. Is there something I should be aware of in regards to Rails or the manner in which I'm ignoring files? Also, if there is an easier way I should reproduce this for you, let me know. :bow:

## Environment

- **Ruby**: 3.1.0
- **Zeitwerk**: 2.5.3
- **Rails**: 6.1.4.4

**Comment by fxn** [comment]
Interesting. Let's do a couple of things.

First, in order to ignore `lib/spec` you should ignore the directory:

```ruby
loader.ignore "#{__dir__}/spec"
```

That use case you linked to in the docs is thought for projects that have tests and code mixed. In this case, they are in their own separate folder and `lib/spec` should NOT define a `Spec` module. So, you need to ignore the directory itself.

With that change in place, could you please enable logging

```ruby
loader.log!
```

reproduce, and share the traces?

**Comment by fxn** [comment]
Oh, I see it.

The directory is `#{__dir__}/git_plus/spec`, not `#{__dir__}/spec`. So, your original glob pattern was actually not ignoring anything. And this showed up when Rails eager loaded.

**Comment by fxn** [comment]
So, to summarize:

1. You have to ignore the directory to tell Zeitwerk `lib/git_plus/spec` does not define anything, not even `GitPlus::Spec`.
2. And you don't need a glob pattern.
3. Just `loader.ignore "#{__dir__}/git_plus/spec"`.

**Comment by bkuhlmann** [comment]
Ha, yep! Thanks. :bow: Seems so obvious now in hindsight. I'm going to close this issue since it's due to user error on my part. I also forgot about the use of `#log!`. I will make sure to leverage that more in the future. Thanks again!
