### ISSUE TITLE
Using auto-(re-)loadable Constants in Rails initializers

### ISSUE THREAD

**Issue by oneiros** [fxn/zeitwerk#212]
Sorry for asking what might be an obvious question. I really enjoy working with zeitwerk and all in all I find the documentation and dev experience to be excellent.

But now I am trying to wrap my head around a seemingly small problem in a large legacy code base that I need to update to Rails 7.

I read the Rails guides and the discussion in https://github.com/rails/rails/issues/40904. I get the configuration examples, where `to_prepare` is necessary. And I get that sometimes code just is not "autoloadable".

But I think I have a third kind of case: In the app I am working on someone implemented a kind of "fail-safe" oder "sanity check" that is supposed to run once when the application is booted.

I cannot share the actual code but consider the following example of a file `config/initializers/check_role_presence.rb`:

```ruby
unless Role.where(name: "admin").exists?
  raise "Important data is missing from the database. Please run `rails db:seed`."
end
```

This code should really run only once (and not all of the time as it would in a `to_prepare` block). And `Role` does not get mutated, so it can still be auto- and reloaded without negative consequences.

As I said, the actual code is different, and my job in this case is not to criticize past decisions, just to make it work with rails 7. So I wonder if there is something obvious I am missing.

**Comment by casperisfine** [comment]
You can use `after_initialize` instead of `to_prepare`, it will only run once.

On a sidenote, connecting to the DB as part of the boot process is not a good idea for resiliency reasons. So you'd likely want to scope this code for dev/test only.

**Comment by oneiros** [comment]
> You can use `after_initialize` instead of `to_prepare`, it will only run once.

Thank you so, so much. This was exactly what I was looking for.

**Comment by fxn** [comment]
🙌 thanks for your kind words!

**Comment by fxn** [comment]
I have documented this use case in https://github.com/rails/rails/commit/ee907fc38e7615b9fda23b288828de7af119ea40. Also backported to `7-0-stable`.
