### ISSUE TITLE
LoadError

### ISSUE THREAD

**Issue by Bukenco** [fxn/zeitwerk#213]
Hello there

I add gem into the project. I have added configuration as well. Locally works fine, but when I deploy it on the development machine, then I'm getting error: /lib/zeitwerk/kernel.rb:35:in require': cannot load such file -- google/ads/google_ads/api_versions (LoadError)`

My configuration file:

`
require "google/ads/google_ads"

Google::Ads::GoogleAds::Config.new do |c|
c.treat_deprecation_warnings_as_errors = false
c.warn_on_all_deprecations = false

c.developer_token = Rails.application.secrets.dev_token

c.client_id = Rails.application.secrets.google_client_id
c.client_secret = Rails.application.secrets.google_client_secret
c.login_customer_id = Rails.application.secrets.google_login_customer_id

c.log_level = 'WARN'
c.log_target = STDOUT
end`

When I run zeitwerk:check on my local machine everything is fine.
When I run zeitwerk:check on development machine, I got the errors: LoadError: cannot load such file -- google/ads/google_ads

Any help?

**Comment by fxn** [comment]
Hi.

Zeitwerk [decorates `Kernel#require`](https://github.com/fxn/zeitwerk/blob/main/lib/zeitwerk/kernel.rb), and that is why you see it in the traces, but this problem is unrelated to Zeitwerk.

The Rails autoloaders do not autoload gems like that one. You probably need to fix your `Gemfile`.

**Comment by fxn** [comment]
> You probably need to fix your Gemfile.

Maybe not. The `require` that is missing is the one for `google/ads/google_ads/api_versions`, and that seems to be loaded by `google/ads/google_ads` [here](https://github.com/googleads/google-ads-ruby/blob/main/lib/google/ads/google_ads.rb#L18).

So, you might need to dig a bit into that gem, but I believe we can close here.
