### ISSUE TITLE
Rails.configuration.to_prepare

### ISSUE THREAD

**Issue by ttqtrang146** [fxn/zeitwerk#217]
I'm updating from redmine 4 to redmine 5. When updating a plugin, it didn't work. I think the plugin's libraries couldn't be loaded. In the plugin's init.rb file, it's configured below
`Rails.configuration.to_prepare do #ActiveSupport::Reloader.to_prepare`
    `User.send :include, Patch::UserPatch`
    `ApplicationController.send :include, Patch::ApplicationControllerPatch`
`end`
So, what will be replaced for Rails.configuration.to_prepare in Zeitwerk?

**Comment by fxn** [comment]
Hi! That is related to Rails itself, I've created https://github.com/rails/rails/issues/45176 for it.
