### ISSUE TITLE
Since `v2.6.0`, instructions for "reopening third-party namespaces" are incomplete

### ISSUE THREAD

**Issue by nickcampbell18** [fxn/zeitwerk#221]
Hi folks,

Just to let you know that following the README instructions for ["Reopening third-party namespaces"](https://github.com/fxn/zeitwerk#reopening-third-party-namespaces) will trigger a warning since `v2.6.0`.

[GoodJob](https://github.com/bensheldon/good_job) have implemented Zeitwerk exactly as those instructions said, and have been bitten by this problem - they are discussing mitigations here: https://github.com/bensheldon/good_job/issues/616.

(I don't know what the fix is or even really deeply understand the problem space, but thought you would like to know!)

**Comment by fxn** [comment]
You're right, docs have been revised in 9daa7b8e8f46d98af3cb79f13e1a44e0177c8b10.
