### ISSUE TITLE
Reload is not worked with roda.

### ISSUE THREAD

**Issue by zw963** [fxn/zeitwerk#23]
### folder directory:

├── app.rb
├── config.ru
├── Gemfile
└── Gemfile.lock

### content of config.ru

```rb
require 'roda'
require 'zeitwerk'

::Loader = Zeitwerk::Loader.new
::Loader.logger = method(:puts)
::Loader.push_dir(__dir__)
::Loader.setup

run App
```

### content of  app.rb

```rb
class App < Roda
  route do |r|
    p Loader.reload  # <= i am very ensure this code invoked repeatedly when send request.
    r.root do
      'hello1'
    end
  end
end
```

### content of Gemfile

```rb
# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "roda"
gem 'zeitwerk'
```

### start up server

```sh
$: rackup
Zeitwerk@3ff636: autoload set for App, to be loaded from /home/zw963/Kid17/mastering_roda/my_app/app.rb
Zeitwerk@3ff636: constant App loaded from file /home/zw963/Kid17/mastering_roda/my_app/app.rb
[2019-03-17 00:52:12] INFO  WEBrick 1.4.2
[2019-03-17 00:52:12] INFO  ruby 2.6.1 (2019-01-30) [x86_64-linux]
[2019-03-17 00:52:12] INFO  WEBrick::HTTPServer#start: pid=29575 port=9292
```

### first time visit http://127.0.0.1:9292/ in browser

logs:

```sh
Zeitwerk@eb920c: App unloaded
Zeitwerk@eb920c: autoload set for App, to be loaded from /home/zw963/Kid17/mastering_roda/my_app/app.rb
true
127.0.0.1 - - [17/Mar/2019:00:53:48 +0800] "GET / HTTP/1.1" 200 6 0.0013
```
i can see 'hello1' is print in browser, this expected behavior.

### change code from 'hello1' to 'hello2' in app.rb, visit http://127.0.0.1:9292/ again

logs:

```sh
Zeitwerk@eb920c: autoload for App removed
Zeitwerk@eb920c: autoload set for App, to be loaded from /home/zw963/Kid17/mastering_roda/my_app/app.rb
true
127.0.0.1 - - [17/Mar/2019:00:54:53 +0800] "GET / HTTP/1.1" 200 6 0.0006
```

### expected behavior

browser print "hello2"

### actually behavior

browser no change, still "hello1"

Thanks

**Comment by fxn** [comment]
On my phone.

You don’t see the changes because Rack evaluated `App` in `config.ru` at boot and therefore it is using always the same class object.

For it to work, you need to add an indirection: It could be as easy as running a lambda `run ->(env) { App.call(env) }` (untested, off the top of my head).

Please let me know if that helps.

**Comment by fxn** [comment]
Followup (still on my phone). If you want to reload on each request, the `reload` call would go at the beginning of the request, something like (untested)

```
# config.ru
loader = Zeitwerk::Loader.new
loader.push_dir(__dir__)
loader.setup

run ->(env) {
  loader.reload
  App.call(env)
}
```

You have to remove then loader calls in the rotes.

**Comment by zw963** [comment]
It worked now like a charm! Thanks.

**Comment by zw963** [comment]
Still have a question about performance.

for roda, we don't need hot reloader in production,
if we don't need eager_load too, for this case, 
just comment  loader.reload as this:

```ruby
# config.ru
require 'roda'
require 'zeitwerk'

loader = Zeitwerk::Loader.new
loader.logger = method(:puts)
loader.push_dir(__dir__)
loader.setup

run ->(env) {
  loader.reload unless ENV['RACK_ENV'] == 'production'
  App.call(env)
}
```

is there have any performance penalty?

Thanks

**Comment by fxn** [comment]
Probably negligible, but this alternative would be 👌 (untested):

```ruby
if ENV['RACK_ENV'] == 'production'
  Zeitwerk::Loader.eager_load_all
  run App
else
  run ->(env) {
    loader.reload
    App.call(env)
  }
end
```

See? Since you know at boot which is the environment, you can fine tune exactly which application you want to run, the lambda wrapper, or `App`. Also, this gives you a natural place for eager loading.

**Comment by zw963** [comment]
This is the best auto reload solution among the nearly ten solutions I tried, thank you!

To make it easier for other people to read or copy it, following is this awesome solution.

```rb
# config.ru
require 'roda'
require 'zeitwerk'

loader = Zeitwerk::Loader.new
loader.logger = method(:puts)
loader.push_dir(__dir__)
loader.setup

if ENV['RACK_ENV'] == 'production'
  Zeitwerk::Loader.eager_load_all
  run App
else
  run ->(env) {
    loader.reload
    App.call(env)
  }
end

**Comment by zw963** [comment]
Hi, the above idea was extract into a ruby gem since one years ago, with extra bonus: autoload automatically if some file was changed. Please check: https://github.com/zw963/hot_reloader.

A dead simple ruby code hot reloader wrap around [zeitwerk](https://github.com/fxn/zeitwerk) and [listen](https://github.com/guard/listen).

hope can help someone develop with Roda more easiler,  anyway, we don't want missing autoload feature from rails anymore!

**Comment by will** [comment]
Thanks, I also ran into this issue, and this issue helped me.

**Comment by will** [comment]
Actually, I ran into a problem where Zeitwerk was saying that a file didn't define a constant, even though it did, while using this as my config.ru with puma and Roda.

``` ruby
# frozen_string_literal: true

require_relative "config/environment" # not a rails app, but using the same conventions

if Config.allow_code_reloading?
  run ->(env) do
    RELOAD.call # this is defined in a zeitwerk initializer
    Web.call(env)
  end
else
  run Web.freeze.app
end
```

in the initializer
``` ruby
# ...
if Config.allow_code_reloading?
  loader.enable_reloading

  RELOAD = -> { loader.reload }
end
```

Using puma with a max of one thread `-t 1:1` fixed the problem, and also wrapping the reload and call in a mutex also fixed it.

``` ruby
if Config.allow_code_reloading?
  mutex = Mutex.new
  run ->(env) do
    mutex.synchronize do
      RELOAD.call
      Web.call(env)
    end
  end
else
  run Web.freeze.app
end
```

which was confusing to me, because I was under the impression that Zeitwerk was thread safe. Maybe not on reloading?

**Comment by fxn** [comment]
Exactly:

> Zeitwerk is also able to reload code, which may be handy while developing web applications. Coordination is needed to reload in a thread-safe manner. The documentation below explains how to do this.

See also https://github.com/fxn/zeitwerk#reloading.

**Comment by will** [comment]
Thanks! I swear I read through the readme a few times while putting this into my project, but must have had that part slip out of my memory :)

**Comment by fxn** [comment]
No prob, and great to know you're using the lib with Roda :).
