### ISSUE TITLE
Convention on using loaders?

### ISSUE THREAD

**Issue by faraaz-deepsource** [fxn/zeitwerk#234]
Is there a convention on how a file creating and executing the loaders should be required?

for example I have an `initializer.rb` like this:

```ruby
require 'zeitwerk'  

loader = Zeitwerk::Loader.new
loader.push_dir('config')
loader.setup
loader.eager_load
```

 that adds the dirs in the loader and calls `eager_load`. this `initializer.rb` just gets `require_relative`d and the autoloading is done as a "side effect". 

Is there a convention on writing a file that declares loaders like this or should I put it in a class and call `Initializer::initialize()`?

**Comment by faraaz-deepsource** [comment]
its a non-rails, non-gem project

**Comment by fxn** [comment]
Not really, and that setup looks clear and good to me.

The only potential caveat I see is that the argument "config" is relative, which means relative **to the CWD**. This is fine if you control the CWD, but otherwise an absolute path is the way to go. For example:

```ruby
loader.push_dir("#{__dir__}/config")
```

**Comment by faraaz-deepsource** [comment]
Understood. Thank you have a nice day!
