### ISSUE TITLE
Code comment documentation format

### ISSUE THREAD

**Issue by steakknife** [fxn/zeitwerk#236]
What is it using? It looks like some sort of Java or TS doc format rather than yard or rdoc, and there's apparent no mention of it.

I'm wondering why yard wasn't used because there's `yard2steep` and `sord`.

**Comment by fxn** [comment]
Good point. It is [RBS syntax](https://github.com/ruby/rbs/blob/master/docs/syntax.md) and that is now documented in [PROJECT_RULES.md](https://github.com/fxn/zeitwerk/blob/main/PROJECT_RULES.md).

These annotations are not meant for public consumption, it is internal documentation. The signature of the public interface is documented in the README in English when it matters.
