### ISSUE TITLE
Zeitwerk not loading children of struct namespaces

### ISSUE THREAD

**Issue by BroiSatse** [fxn/zeitwerk#273]
### Reproduction setup

File lib/a.rb
```
A = Struct.new(:a)
```

File lib/a/b.rb
```
class A::B
end
```

File start.rb:
```
require 'zeitwerk'
require 'pry'

loader = Zeitwerk::Loader.new
loader.push_dir(File.join(File.dirname(__FILE__), 'lib'))
loader.setup # ready!

puts A::B.name
```

### Expected output
Program to print 'A::B'

### Received output
```
start.rb:8:in `<main>': uninitialized constant A::B (NameError)
```

### Notes
Replacing `lib/a.rb` file with regular (non-struct) class/module definition seems to be working just fine, so does requiring `lib/a/b.rb` file manually.

Zeitwerk version: 2.6.11
Ruby 3.0.5

**Comment by BroiSatse** [comment]
Actually it seems to be an issue with all dynamically created classes. Using `A = Class.new` also seem to prevent children files from being loaded.

**Comment by fxn** [comment]
Yes, unfortunately this is a limitation in explicit namespaces, documented [here](https://github.com/fxn/zeitwerk#edge-cases). This limitation does not exist for classes or modules that are not namespaces.

I have not tested this, but in principle you should be able to subclass:

```ruby
class A < Struct.new(:a)
end
```

Indeed, it would be a nice addition to the docs.

**Comment by BroiSatse** [comment]
@fxn Sorry for the late response - only just saw your answer. That's a fantastic explanation! I wonder if this could be worked-out by monkey patching `Module.new` and `Struct.new` methods (which seems not to be executed when creating modules/classes in traditional way). I'd imagine this could be wrapped in a helper module and maybe configurable as well?
