### ISSUE TITLE
drb was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0

### ISSUE THREAD

**Issue by diei** [fxn/zeitwerk#288]
After update to Ruby 3.3.0 I get the following message:

`~/.rvm/gems/ruby-3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/kernel.rb:34: warning: drb was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add drb to your Gemfile or gemspec. Also contact author of zeitwerk-2.6.13 to add drb into its gemspec.`

**Comment by fxn** [comment]
Hey, Zeitwerk does not use `drb`. Problem is this warning assumes the caller of `Kernel#require` is the one that wants to use the gem. But this might not be the case.

Does your project use `drb`?

**Comment by diei** [comment]
Thanks for the hint. It seems that `rspec` and `activesupport` use `drb`. Maybe the message disappears when these gems are updated.

**Comment by fxn** [comment]
For the time being, you can add `drb` to your Gemfile.
