### ISSUE TITLE
Error when using in Ractor

### ISSUE THREAD

**Issue by ukolovda** [fxn/zeitwerk#291]
Ruby 3 introduced Ractor, allowing utilize more than 1 core of CPU.

But when I try use it (make second instance of Rails Application), I got the error:

`ruby-3.2.3/gems/zeitwerk-2.6.13/lib/zeitwerk/registry.rb:122:in `loader_for': can not get unshareable values from instance variables of classes/modules from non-main Ractors (Ractor::IsolationError)`

Full test code:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"
end

require "active_support"
require "active_support/core_ext/object/blank"
require "minitest/autorun"

class TestApplication < Rails::Application
end

# Workaround of Railties error
Ractor.make_shareable(Rails::Railtie::ABSTRACT_RAILTIES)

main_app = Rails.application

class BugTest < Minitest::Test
  def test_stuff

    r = Ractor.new do
        app2 = TestApplication.new
    end

  end
end
```

Ruby 3.2.3

I don't sure that my approach is correct, but we can create multiple instance of application, it can reduce RAM usage for many applications in the world.

**Comment by fxn** [comment]
Ractors cannot even do concurrent `require`:

```ruby

**Comment by casperisfine** [comment]
To add to this, if you want to use Ractors, you should eager load your application, that's easy to do with Zeitwerk.
