### ISSUE TITLE
NameError only on Ubuntu/Rails 7.2

### ISSUE THREAD

**Issue by brevio-nicolay** [fxn/zeitwerk#306]
Hello, thank you for the excellent library!

I'm running into an issue when running our test suite on an Ubuntu box in the CI environment.

We use a home-made loader for our test environment which allows us to be a tad more terse in our test files:

```ruby
# test.rb
module Test; end

class BrevioInflector < Zeitwerk::Inflector # rubocop:disable Lint/ConstantDefinitionInBlock
  def camelize(basename, abspath)
    if basename =~ /(.*)api$/
      super($1, abspath) + 'API'
    else
      super
    end
  end
end

loader = Zeitwerk::Loader.new
loader.inflector = BrevioInflector.new
test_dir = "#{Rails.root}/test"

loader.push_dir(test_dir, namespace: Test)

loader.ignore("#{test_dir}/test_helper.rb")
loader.ignore("#{test_dir}/factories")

loader.setup
```

The test in question:

```ruby
# <Rails.root>/test/access_token_test.rb
class Test::AccessTokenTest < ActionDispatch::IntegrationTest
```

This works perfectly locally, but raises the following error on our CI builds:

```
/home/runner/actions-runner/_work/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/cref.rb:60:in `const_get': uninitialized constant Test::AccessTokenTest (NameError)
```

Unsure of whether there's something I'm missing or doing wrong here (the setup works fine locally on OSX, and worked fine on our ubuntu CI servers until I upgraded to Rails 7.2).

Again, thanks for all the great work 👍

**Comment by brevio-nicolay** [comment]
The problem was this line in `test.rb`:

``` 
config.eager_load = ENV['CI'].present?
```

It was **above** the loader defined below, which meant the namespaces weren't properly handled yet. Moving the loader above the eager load setting solved the problem.

**Comment by fxn** [comment]
Hi! That is strange.

`config.eager_load` only sets a configuration value. That value is used by the end of the boot process, but not during the evaluation of `test.rb`. Within that file, the relative order of those lines should not matter in theory.

Could there be something else?

**Comment by brevio-nicolay** [comment]
Yeah, I realised after I closed the issue that I missed some lines WRT namespace eager loading. The issue disappeared because I had added those lines as well (though I hadn't realised 😅).
