### ISSUE TITLE
`resolve-replace` warning

### ISSUE THREAD

**Issue by ch-minhvu** [fxn/zeitwerk#309]
Hi, currently a project that I am working on that uses `zeitwerk 2.7.1` is throwing this warning. I believe that `resolve-replace` will no longer be part of ruby standard lib starting from 3.4.0 so would it be possible for `zeitwerk` to update its gemspace according to the warning suggestion?

![image](https://github.com/user-attachments/assets/b85b27e1-b768-4bb7-9e60-aa515b6fc208)

**Comment by fxn** [comment]
Hey @ch-minhvu Zeitwerk does not use that gem, unfortunately Ruby is pointing to the wrong place, you'll need to figure out who is loading `resolv-replace`.
