### ISSUE TITLE
zeitwerk (1.4.3) Rails 6 beta 3, killer bug

### ISSUE THREAD

**Issue by webzorg** [fxn/zeitwerk#33]
So I did `bundle update` and it went as usual, like a butter. Then I started rails server changed lot of things and took 20 trials to zero down to this gem. To reproduce, just change any controller or model or any rb file, no matter what the change is, even if there is no change (change-save undo-save), then the weird errors like constant User is undefined started popping out. Basically whole app code got lost. If you restart server it works again, until you make a first rb file related change, same again. Reverted to 1.4.2 to avoid this hell.

**Comment by fxn** [comment]
Which is your version of bootsnap?

**Comment by webzorg** [comment]
`bootsnap (1.4.1)`

**Comment by webzorg** [comment]
Ironically, I just read `Faster reload. If you're using bootsnap, requires at least version 1.4.2.` I guess I will try this tomorrow. and problem resolved for now! thanks!

**Comment by fxn** [comment]
It squares.

Let's see tomorrow!

**Comment by webzorg** [comment]
Ok confirmed fixed, and reloads are feeling faster too yay xD

**Comment by fxn** [comment]
Awesome, thanks for opening an issue anyway!
