### ISSUE TITLE
Idea: Strict mode?

### ISSUE THREAD

**Issue by casperisfine** [fxn/zeitwerk#37]
👋 I'm currently clearing up all the `shadowed_files` in our app, and I'm thinking: is a log actually enough? I'm concerned that users might re-introduce this kind of problems after I cleared them.

Feels to me that a shadowed file it's very likely to be indicative of an error, or at least not be what the user expect.

Is there legitimate reasons for files to be shadowed? Couldn't we more explicitly throw an error  when it happens? Possibly as a `Loader#strict = true` option?

**Comment by casperisfine** [comment]
Alternatively:

`Loader#logger` could be an actual `::Logger` and these could be logged as `warnings` / `errors` while the other stuff could be logged as `debug`.

**Comment by fxn** [comment]
This is something I have pondered a few times. By now it is the way it is because for me Z is about automating `require`, sometimes you shadow on purpose in Ruby, and Ruby does not warn either. So that is my current model: act as Ruby.

Real-world usage may change that though, open to revise but need evidence of its convenience.

Why does your app have so many shadowed? Did they autoload before?

**Comment by casperisfine** [comment]
Most of the shadowed where constants loaded by `AS::Dependencies` from `config/initializers` before Zeitwerk kicks in. If fixed all of these (calling `AS::Dependencies.unhook!` super early helped a ton), and I'm now left with a handful a cases (~12).

One example, we had an ActiveSupport::Cache backend in `eagerlib/foo_backend.rb`, it's required from `config/application.rb` because it's set in Rails config.

Overall it works, but `eagerlib` is a reloadable path, so I'm worried it sets wrong expectations, I'd rather have it outside of the autoloader paths.

**Comment by fxn** [comment]
I have pending your patch in Rails re initialization.

I don't have yet decided if I prefer to update `$LOADED_FEATURES` or force an unload before Z taking over, but we are going to warn in Rails about those constants.

I think I prefer to close this one by now to keep open tickets low. Prefer to address that use case in Rails.

That said, if experience tells us there are other use cases that deserve this I might consider reopening.

**Comment by casperisfine** [comment]
Works for me 👌
