### ISSUE TITLE
Reload from nested subdirectories

### ISSUE THREAD

**Issue by sandelius** [fxn/zeitwerk#4]
Hello there and thank you for the awesome work with this gem. I'm trying this on a non-rails project and have some issues with code-reloading. It loads the files just fine but wont reload them and I cannot see them in the `@autoloads` array.

My directory structure is:

```
apps
  web
    controllers
      books.rb
```

```ruby
# apps/web/controllers/books.rb

module Web::Controllers
  class Books
    # ...
  end
end
```

My loader is setup like this:

```ruby
loader = Zeitwerk::Loader.new
loader.push_dir("/path/to/lib")
loader.push_dir("/path/to/apps")
loader.setup

# And in a middleware I call (it's the same instance as the one above)
loader.reload
```

The files in `lib` gets reloaded but not in apps. If I would guess this has something to do with the "empty" namespace between `Web::Controllers`.

Am I missing something, has this something to do with the rails concerns compatibility?

This is what I get when I inspect the loader:

```ruby
#<Zeitwerk::Loader:0x00007fdb978cf198 @inflector=#<Zeitwerk::Inflector:0x00007fdb978cf148>, @dirs={"/path/to/sandbox/lib"=>true, "/path/to/sandbox/apps"=>true}, @preloads=[], @ignored=#<Set: {}>, @autoloads={"/path/to/sandbox/lib/sandbox/message.rb"=>[Sandbox, "Message"], "/path/to/sandbox/apps/web"=>[Object, "Web"]}, @lazy_subdirs={"Web"=>["/path/to/sandbox/apps/web"]}, @eager_load_exclusions=#<Set: {}>, @mutex=#<Thread::Mutex:0x00007fdb978cef40>, @setup=true, @eager_loaded=false, @tracer=#<TracePoint:enabled>>
```

**Comment by fxn** [comment]
Thanks very much for trying the beta! ❤️ 

The setup seems fine. In what sense they are not reloaded? Do you get `NameError`s on subsequent requests?

The inspected object looks fine to me in principle. There is an autoload configured for `/path/to/sandbox/apps/web`, and the namespace is going to be processed on demand, whenever some code path accesses the `Web` module.

"Reloading" means unloading what had been loaded, and running `setup` again, so the internal state of the loader looks again as in the beginning except for possible changes in the file system. It is going to be ready doing as less work as possible.

Does that make sense?

**Comment by fxn** [comment]
In case it helps, logging in `master` now prints traces while reloadng. You should see new messages for autoloads removed, and for loaded objects unloaded.

**Comment by sandelius** [comment]
Hi again and thank you for the quick response.

I figured it out and it was that i load the `Web::Controllers::Books` class before Rack is running. If I load it within `#call` it works as expected.

This is not an issue so I'll close it for you 👍

**Comment by fxn** [comment]
Perfect!

Makes sense, for example if a web framework loads controllers when building routes and stores the class objects or instances in an internal structure, those become stale instances if reloading. The framework is responsible in that case for reloading the routes themselves as well. Rails does this for example.

Thanks for the followup!

**Comment by sandelius** [comment]
> Perfect!
> 
> Makes sense, for example if a web framework loads controllers when building routes and stores the class objects or instances in an internal structure, those become stale instances if reloading. The framework is responsible in that case for reloading the routes themselves as well. Rails does this for example.
> 
> Thanks for the followup!

Exactly. When I evaluate routes it uses `Object.const_get` so that process does not need happen during runtime (each request). Right now I changed to do this during runtime until I have time to figure out a better approach for this.
