### ISSUE TITLE
deleting a folder results in an error

### ISSUE THREAD

**Issue by localhostdotdev** [fxn/zeitwerk#42]
absolutely not blocking but a bit interesting

I deleted my mailers folder and got this:

```
Errno::ENOENT
No such file or directory @ dir_initialize - /Users/localhostdotdev/src/my-app/app/mailers
```

**Comment by fxn** [comment]
When did you do this? Was it while the server was running?

**Comment by localhostdotdev** [comment]
yes, I did this while `rails server` (e.g. puma) was running

**Comment by fxn** [comment]
I think that use case could be supported, let me think a bit about it.

**Comment by fxn** [comment]
Added support for this use case in bde79812d11eeb102e0045eb6e1b28fbf968ca4a. Version 2.1.4 includes this, just published.

**Comment by localhostdotdev** [comment]
very nice, thanks! it also appended on a `rails generate` because the app was loaded with spring so that will fix that too
