### ISSUE TITLE
Reloading, autoloading and thread safety

### ISSUE THREAD

**Issue by sponomarev** [fxn/zeitwerk#52]
Hi there!

At first, thanks for such a great project! We're finally able to overcome Rails autoloading gotchas and, moreover, bring autoloading and reloading to our non-Rails projects.

Appreciate your outstanding work! I've watched your presentation on Stuart-Tech and was even more inspired.

At the moment I'm experimenting with Zeitwerk + Rack (Cuba). Autoloading works like a charm but I have an issue with code reloading in a multithreaded environment. The docs say that reloading itself is not thread-safe and it's my responsibility to coordinate it which definitely makes sense. 

To be able to reload code between requests in Rack I've implemented a very trivial middleware:

```ruby
  class Reloader
    def initialize(app, loader)
      @app = app
      @loader = loader
      @mutex = Mutex.new
    end

    def call(env)
      @mutex.synchronize { @loader.reload }
      @app.call(env)
    end
  end
```

Unfortunately, it doesn't help and I still see errors like that:

```
web_1      | 2019-05-15 04:36:43 +0000: Rack app error handling request { GET /sidekiq/stylesheets/bootstrap.css }
web_1      | #<ArgumentError: wrong number of arguments (given 0, expected 2)>
web_1      | /bundle/gems/zeitwerk-2.1.6/lib/zeitwerk/loader.rb:655:in `cpath'
web_1      | /bundle/gems/zeitwerk-2.1.6/lib/zeitwerk/loader/callbacks.rb:11:in `on_file_autoloaded'
web_1      | /bundle/gems/zeitwerk-2.1.6/lib/zeitwerk/kernel.rb:17:in `block in require'
web_1      | /bundle/gems/zeitwerk-2.1.6/lib/zeitwerk/kernel.rb:16:in `tap'
web_1      | /bundle/gems/zeitwerk-2.1.6/lib/zeitwerk/kernel.rb:16:in `require'
web_1      | /bundle/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
web_1      | /bundle/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
web_1      | /bundle/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
web_1      | /app/config/routes.rb:24:in `block (3 levels) in <top (required)>'  # `SidekiqAdmin` class should be loaded on that line
# Unrelated stack
```
It happens because `cref` is not resolved from empty, for some reason, `autoloads`

It happens once and after that, there are code loading issues after the exception:

```
web_1      | Zeitwerk@ed7a8d: file /app/app/web/controllers/sidekiq_admin.rb is ignored because SidekiqAdmin is already defined
```

Does it mean that the autoloading is not thread-safe for some reason?

I assume that becasue when I wrap not only reloading, but also the constant loading in a lock, the problem goes away.

Simplified:

```ruby
    def call(env)
      @mutex.synchronize do
         @loader.reload
         @app.call(env)
      end
    end
```

**Comment by fxn** [comment]
Exactly.

The problem in the original attempt is that if there are two concurrent requests, one wins the mutex, and when it releases the lock it continues serving the request. But while that happens, the other one got the lock and it is reloading. So the first request may assume constant `User` exists, while the second one just removed it.

Basically, there cannot be requests being served concurrently while reloading.

One trivial way to solve this is to serialize all requests, as your last example does. The trade-off is that it hinders parallelism, but it is a cheap and simple solution that in development sometimes can be enough.

Another approach, more complicated, is to do what Rails does. First, you only reload if there are changes in the file system. You can use the [`listen`](https://github.com/guard/listen) gem for that. Then, you need a RW lock. Requests must acquire the lock for reading, and the code that reloads must acquire the lock for writing. With that, you get concurrency as long as the file system does not change. When files are modified, the code in charge of reloading must acquire the lock for writing.

The idea would be:

```ruby
# somewhere
Listen .... do
  acquire_lock_for_writing do
    @loader.reload
  end
end

# main entry point
def call(env)
  acquire_lock_for_reading do
    @app.call(env)
  end
end
```

If files are modified, acquiring the lock for writing will wait until existing requests finish. At the same time, incoming request wanting to acquire the lock for reading will be blocked. That logic is managed by the lock itself.

Thanks for the kind words!

**Comment by fxn** [comment]
Closing here! Hope the explanation helped.

**Comment by sponomarev** [comment]
@fxn I'm sorry for the late response. Thanks a lot for the answer! I was wrong with the assumption that the code reloading is not thread-safe in terms of conflicting to itself and the regular loading, but your explanation clarifies the whole picture to me. Appreciate!

If anybody else reach that tread, I decided to go with the most straightforward "request serialization" solution which works great during development.

**Comment by janko** [comment]
For those looking, concurrent-ruby has a [read/write lock implementation](https://ruby-concurrency.github.io/concurrent-ruby/master/Concurrent/ReadWriteLock.html). I was able to utilize it like this:

```rb
# initialize the global lock
require "concurrent/atomic/read_write_lock"
RELOAD_LOCK = Concurrent::ReadWriteLock.new

# take write lock when reloading code
listener = Listen.to("app") do
  RELOAD_LOCK.with_write_lock do
    loader.reload
  end
end
listener.start

# take read lock around requests (e.g. in config.ru)
run -> (env) do
  RELOAD_LOCK.with_read_lock do
    App.call(env)
  end
end
```

**Comment by fxn** [comment]
@janko fantastic contribution, I have updated the documentation with similar snippets.
