### ISSUE TITLE
Unintuitive Inflector Behavior

### ISSUE THREAD

**Issue by klobuczek** [fxn/zeitwerk#59]
You might want to consider using `capitalize` instead of `capitalize!` in Inflector.
`capitalize!` returns `nil` if nothing has been changed which causes an entire part of the name to be swallowed. 
e.g. `point_3d_value` is camelized to `PointValue`

**Comment by fxn** [comment]
The inflector is extremely delicate, but I agree, and doubt is going to break existing code.

**Comment by fxn** [comment]
Just published 2.1.7 including this commit.
