### ISSUE TITLE
uninitialized constant Concerns (NameError)

### ISSUE THREAD

**Issue by astrocket** [fxn/zeitwerk#60]
For version 2.1.7, when I run rails application as production mode like below
`RAILS_ENV=production rails s`

zeit raises exception like below
`uninitialized constant Concerns (NameError)`

It works fine on 2.1.6.

I only have .keep files under all `concerns` directories.

**Comment by Fudoshiki** [comment]
same

**Comment by fxn** [comment]
2.1.8 fixes it.
