### ISSUE TITLE
Loader error on ignored paths

### ISSUE THREAD

**Issue by kvokka** [fxn/zeitwerk#65]
Steps to reproduce:

```
# my_gem
loader = Zeitwerk::Loader.for_gem
loader.ignore 'lib/foo/bar'
loader.setup
```

Later, in another file:
```
# lib/foo/bar/zoo/my_file
loader = Zeitwerk::Loader.new
loader.push_dir "#{__dir__}/active_record" # <= raised here
loader.setup
```

It looks like the problem is in `Loade::raise_if_conflicting_directory(dir)` method. Don't you mind if I'll take it for PR?

**Comment by fxn** [comment]
I don't fully undersand. Are you instantiating a loader inside an ignored path of the same project?

**Comment by kvokka** [comment]
Thank you for a such a quick response.

Sorry, it is looking like the initial description was clumsy.

Yes. I'm Implementing the adapter pattern (in the gem, but it does not the case). I followed this https://github.com/fxn/zeitwerk#use-case-the-adapter-pattern part of the documentation, and it was ended with `require` which loads the adapter. But the adapter may load some assets specific for this adapter. And I want to load this assets with another instance of zeitwerk (this path was ignored in the very beginning by main loader).

At this moment I realized, that it is really edge use case.

I'll try to handle it. Don't you mind if I also add this case in the README?

**Comment by fxn** [comment]
It would help me understand the use case better if you could share some real files. At least a bunch of real file names (contents not needed). I get the idea of what you're doing, but that would be even better if possible.

**Comment by kvokka** [comment]
No problem

```ruby
# lib/active_validation.rb
loader = Zeitwerk::Loader.for_gem
loader.ignore 'lib/active_validation/frameworks'
loader.setup
```

```ruby
# lib/active_validation/orm_adapters/active_record.rb
# The adapter file
...

# If the adapter is loaded, it load the assets
require 'active_validation/frameworks/active_record'
```

```ruby
# lib/active_validation/frameworks/active_record.rb
loader = Zeitwerk::Loader.new
loader.push_dir "#{__dir__}/active_record/models"
loader.setup
```

**Comment by kvokka** [comment]
I made my tests green with local patch of `zeitwerk` gem, but did not write the tests for `zeitwerk` yet and the additions for the docs. Will try to deal with it today later and give you a PR

**Comment by kvokka** [comment]
You closed my PR, so i have to write here.

You wrote in #67 message "But the current check is not taking into account ignored paths. Anything below an ignored path is in particular not managed by that loader, so there is no conflict if a different loader wants to."

It is sad to mention, but this PR add exactly this functionality. If you would like, you can run included test only with out the code base change and see, that it is red. And the patch fix it.

The docs, now, do not offer nothing better than use a `require` with adapter pattern (and it is ok while we are talking about 1 file).

**Comment by kvokka** [comment]
i already got working solution with out any changes in zeitwerk

```
loader = Zeitwerk::Loader.for_gem
loader.ignore "#{__dir__}/my_gem/orm_plugins"
loader.enable_reloading
loader.setup

# in the adapter, with the same loader instance
loader.push_dir "#{__dir__}/my_gem/orm_plugins/active_record_plugin/models"
loader.reload
```

but it is good enough for dev only. #67 resolved it.

If you know, how to do it better, please, share this information with me.

Thank you!

**Comment by fxn** [comment]
> It is sad to mention, but this PR add exactly this functionality. If you would like, you can run included test only with out the code base change and see, that it is red. And the patch fix it.

I have to apologize. You're right, guess I am doing too many things this weekend.

I somehow believed that this was a documentation patch. Perhaps I opened it days ago, only checked the first chunk visible in the browser window, and mistakenly remembered later as a doc patch only.

Why does your docs say the inner loader has to eager load?

**Comment by kvokka** [comment]
No worries :)

You right, my bad. eager_load is not mandatory. I'll fix it in a moment

**Comment by kvokka** [comment]
#68
