### ISSUE TITLE
Zeitwerk trying to autoload YAML files since 2.1.9

### ISSUE THREAD

**Issue by thelucid** [fxn/zeitwerk#72]
Since upgrading to Rails 6 from 6.rc2, I'm getting an error whereby Zeitwerk is truing to autoload a YAML file placed in `my-rails-app/some-dir/some-subdir/1-my-file.yml.

Framework trace is:

```
NameError: wrong constant name 1-my-file
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:705:in `const_defined?'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:705:in `cdef?'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:610:in `strict_autoload_path'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:587:in `autoload_for?'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:501:in `autoload_subdir'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:490:in `block in set_autoloads_in_dir'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:662:in `block in ls'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:659:in `foreach'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:659:in `ls'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:476:in `set_autoloads_in_dir'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader/callbacks.rb:67:in `block in on_namespace_loaded'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader/callbacks.rb:66:in `each'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader/callbacks.rb:66:in `on_namespace_loaded'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader/callbacks.rb:52:in `block in on_dir_autoloaded'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader/callbacks.rb:39:in `synchronize'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader/callbacks.rb:39:in `on_dir_autoloaded'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.9/lib/zeitwerk/kernel.rb:20:in `require'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:355:in `const_get'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:355:in `block (2 levels) in eager_load'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:662:in `block in ls'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:659:in `foreach'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:659:in `ls'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:346:in `block in eager_load'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:338:in `synchronize'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:338:in `eager_load'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:449:in `each'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:449:in `eager_load_all'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.0/lib/rails/application/finisher.rb:122:in `block in <module:Finisher>'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.0/lib/rails/initializable.rb:32:in `instance_exec'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.0/lib/rails/initializable.rb:32:in `run'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.0/lib/rails/initializable.rb:61:in `block in run_initializers'
~/.rbenv/versions/2.6.3/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
~/.rbenv/versions/2.6.3/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
~/.rbenv/versions/2.6.3/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
~/.rbenv/versions/2.6.3/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
~/.rbenv/versions/2.6.3/lib/ruby/2.6.0/tsort.rb:347:in `each'
~/.rbenv/versions/2.6.3/lib/ruby/2.6.0/tsort.rb:347:in `call'
~/.rbenv/versions/2.6.3/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
~/.rbenv/versions/2.6.3/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
~/.rbenv/versions/2.6.3/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.0/lib/rails/initializable.rb:60:in `run_initializers'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.0/lib/rails/application.rb:363:in `initialize!'
```

**Comment by fxn** [comment]
That is strange, in general any filename that does not have a ".rb" extension is ignored and there is coverage [here](https://github.com/fxn/zeitwerk/blob/757dd734340024e487bd9678dcf80a567064bfdc/test/lib/zeitwerk/test_top_level.rb#L38). Guess something was overlooked, but would need help to find it.

Could you provide a minimal application and reproduction steps?

**Comment by thelucid** [comment]
@fxn Literally the only steps to reproduce are to drop a file in `app/foo/bar/file.yml` and run it in production.

**Comment by thelucid** [comment]
@fxn Thanks for the quick reply btw.

**Comment by thelucid** [comment]
@fxn This looks to be the same issue: https://github.com/fxn/zeitwerk/issues/73.

**Comment by fxn** [comment]
OK, let me check.

**Comment by thelucid** [comment]
@fxn I'm not sure how to access the instance in `application.rb` in the meantime — in order to put an ignore path in.

**Comment by fxn** [comment]
I have created a new Rails 6 app, have created `app/models/foo.yml`, and have executed `bin/rails runner 1`. It did not err.

Could you please create a new Rails 6 app and see which is the minimum we have to do to reproduce?

**Comment by fxn** [comment]
Also, could you throw

```

**Comment by thelucid** [comment]
@fxn Leave it with me.

**Comment by thelucid** [comment]
@fxn I've found the issue I think, just trying to reproduce. The problem seems to come from the fact that there is a model under `app/models/statics/base.rb` and yaml files under `app/statics/1-my-dir/index.yml` etc.

I think it's getting confused that the module exists — shouldn't really matter though.

**Comment by fxn** [comment]
Oh yes, a directory in an autoload path should be a valid namespace, regardless of whether it has any Ruby files beneath (autovivification still works).

Your use case is legit, but you need to ignore the directory. Probably you want to ignore the entire subdirectory of `app` if it contains what the name suggests.

```
Rails.autoloaders.main.ignore("#{Rails.root}/app/statics")
```

**Comment by thelucid** [comment]
@fxn Steps to reproduce:

```
rails new tester
cd tester/
rails g model foo/bar
mkdir -p app/foo/1-baz
touch app/foo/1-baz/file.yml
rails s -e production
```

Weirdly it doesn't error if there is no number in the filename.

**Comment by thelucid** [comment]
@fxn Surely it shouldn't bother creating a module for any directories that have no `.rb` files in it?

**Comment by fxn** [comment]
@thelucid it does not, it sets an autoload for it, and it has to do it because the project could autovivify the module.

Besides, since Zeitwerk is lazy, it does not inspect the contents of the directory until the constant is used. But this is not really the point, even if it did, the autoload has to be set.

The rules of the project structure is that if the directory belongs to the autoload paths, it is a namespace. The only way out of that rule is an explicit ignore.

**Comment by thelucid** [comment]
@fxn I see. Thanks for the clarification. The odd thing is, it worked fine on 2.1.8.

**Comment by fxn** [comment]
Hmmm... that is surprising. For example, I have this minimal example:

```
$ tree .
.
├── lib
│   └── 1
└── test.rb
```

where `test.rb` is

```ruby
gem "zeitwerk", "2.1.8"
require "zeitwerk"

loader = Zeitwerk::Loader.new
loader.push_dir("#{__dir__}/lib")
loader.setup
```

and running the script raises as expected:

```
Traceback (most recent call last):
...
.../zeitwerk-2.1.8/lib/zeitwerk/loader.rb:679:in `const_defined?': wrong constant name 1 (NameError)
```

Could it be the case that the project changed meanwhile?

**Comment by thelucid** [comment]
@fxn I've just done some digging and nothing changed in between upgrading from Rails 6.0.0.rc2 to 6.0.0. I think you'll find that if you run those steps on both versions, one will fail and one won't. The error is `zeitwerk-2.1.9/lib/zeitwerk/loader.rb:705:in `const_defined?': wrong constant name 1-baz (NameError)` which is odd as it's not even camelized.

**Comment by fxn** [comment]
The name is camelized:

```
irb(main):001:0> "1-baz".camelize
=> "1-baz"
```

`camelize` turns snake case into camel case. That directory name has only one segment, since there is no underscore. Hyphens are not snake separators. Then, upcasing "1" gives you "1". So you get a string that is equal to the receiver.

You have two options here:

1. If the directory `app/static` does not represent `Object`, if it does not contain stuff to be autoloaded, you should tell Rails by removing it from the autoload paths:

```ruby
ActiveSupport::Dependencies.autoload_paths.delete("#{Rails.root}/app/static")
```

That has to be set in an application initializer, because the collection is not yet filled before in the boot process. I wish the interface was more amicable, but that is what we have today.

2. If `app/static` does represent `Object` and you are going to autoload from it, but that particular subdirectory should be ignored, then you need to tell Zeitwerk to ignore it:

```ruby
Rails.autoloaders.main.ignore("#{Rails.root}/app/statics/1-my-dir")
```

That can be done in `config/application.rb`.

**Comment by thelucid** [comment]
@fxn Great, thanks. I just wonder if others will encounter it, due to it being a regression — I guess they have this ticket.

**Comment by fxn** [comment]
We have not demonstrated the regression is due to Zeitwerk actually.

This is a Rails issue, more things are involved (should be a Rails ticket, but I didn't mind).

**Comment by fxn** [comment]
If you could provide a minimal application in which this happens in the RC and not in final, we could figure out where's the difference that caused it.

**Comment by thelucid** [comment]
@fxn sure 👍.

**Comment by byroot** [comment]
> we could figure out where's the difference that caused it.

Pretty sure it's due to the change to use `const_get` to eager load.

I think Zeitwerk could automatically ignore directories if the inflector didn't return a valid constant name, or alternatively it could eagerly raise a more explicit error about it.

**Comment by fxn** [comment]
A better error name could be something to explore. It is a trade-off, because that means validating _all_ inflected strings (including Ruby files for consistency, think "1-baz.rb"). We could test which is the impact in performance.

**Comment by fxn** [comment]
I also has a sense of duplicated work, since Ruby validates the names.

Perhaps we could try to do the work in `rescue` clauses... we could see.

**Comment by byroot** [comment]
> We could test which is the impact in performance.

Indeed. I'm far from my actual computer right now, but I'll happily profile that in a few days when I get back.

If the performance impact is too big, we could do it lazily in a rescue.

**Comment by fxn** [comment]
Also starting my holidays tomorrow up to September, enjoy Jean!

**Comment by byroot** [comment]
You too !

In this case, unless you beat me to it, I'll prepare a fix for when you get back.

**Comment by fxn** [comment]
Version 2.1.10 is out an includes that change.
