### ISSUE TITLE
const_defined?': wrong constant name Font-awesome (NameError)

### ISSUE THREAD

**Issue by medicharlachiranjeevi** [fxn/zeitwerk#73]
Hi we are using rails version 6.0.0 and when i run using rails version 6.0.0.rc1 its working fine
Error log 
`
home/system/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:705:in `const_defined?': wrong constant name Font-awesome (NameError)
`

**Comment by fxn** [comment]
Can you please provide a minimal app to reproduce?

**Comment by fxn** [comment]
Can you please share the log of the loader? Just throw

```ruby
Rails.autoloaders.log!
```

in `config/application.rb` and trigger the error.

Where is the directory `font-awesome` located?

**Comment by medicharlachiranjeevi** [comment]
thanks for reply in app/pdf/shared/stylesheets

**Comment by fxn** [comment]
OK, that directory should not be in the autoload paths.

Do you have Ruby code to be autoloaded below `app/pdf` at all?

**Comment by medicharlachiranjeevi** [comment]
Thanks it worked

**Comment by fxn** [comment]
Version 2.1.10 is out an includes that change.
