### ISSUE TITLE
Namespaced models throw uninitialized constant

### ISSUE THREAD

**Issue by hobbypunk90** [fxn/zeitwerk#82]
i have a little problem with my namespaced models:

```ruby
# user/identity.rb
class User::Identity < ApplicationRecord
...
end

# user.rb
class User < ApplicationRecord
...
has_many :identities, class_name User::Identity.name
...
end
```
when i try to start the application with zeitwerk it throws this exeption
```
Uncaught exception: uninitialized constant User (call 'User.connection' to establish a connection)::Identity
```
It works with the classic loader. I have the same problem when i try to use a method on User::Identity in a method in the User class.
Do you have an idea? Is it a problem with my code, or in zeitwerk?

Greets
Marcel

**Comment by fxn** [comment]
That should work, let's see if we find out what's going on.

You say that happens when the application _starts_. Why is the application loading the `User` class on boot? Where does that happen?

**Comment by hobbypunk90** [comment]
Thanks 😁

yes, direct at start, the trace says `devise_for` ist "my" last call.

```
Uncaught exception: uninitialized constant User (call 'User.connection' to establish a connection)::Identity
Did you mean?  Identicon
	/home/hobbypunk/Entwicklung/Eigene_Projekte/DocumentManager/app/models/user.rb:13:in `<class:User>'
	/home/hobbypunk/Entwicklung/Eigene_Projekte/DocumentManager/app/models/user.rb:1:in `<main>'
	/home/hobbypunk/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	/home/hobbypunk/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	/home/hobbypunk/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	/home/hobbypunk/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	/home/hobbypunk/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	/home/hobbypunk/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.10/lib/zeitwerk/kernel.rb:16:in `require'
	/home/hobbypunk/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/inflector/methods.rb:282:in `const_get'
	/home/hobbypunk/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/inflector/methods.rb:282:in `block in constantize'
	/home/hobbypunk/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/inflector/methods.rb:280:in `each'
	/home/hobbypunk/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/inflector/methods.rb:280:in `inject'
	/home/hobbypunk/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/inflector/methods.rb:280:in `constantize'
	/home/hobbypunk/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/dependencies/zeitwerk_integration.rb:19:in `constantize'
	/home/hobbypunk/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/devise-4.7.1/lib/devise.rb:320:in `get'
	/home/hobbypunk/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/devise-4.7.1/lib/devise/mapping.rb:83:in `to'
	/home/hobbypunk/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/devise-4.7.1/lib/devise/mapping.rb:78:in `modules'
	/home/hobbypunk/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/devise-4.7.1/lib/devise/mapping.rb:95:in `routes'
	/home/hobbypunk/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/devise-4.7.1/lib/devise/mapping.rb:162:in `default_used_route'
	/home/hobbypunk/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/devise-4.7.1/lib/devise/mapping.rb:72:in `initialize'
	/home/hobbypunk/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/devise-4.7.1/lib/devise.rb:350:in `new'
	/home/hobbypunk/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/devise-4.7.1/lib/devise.rb:350:in `add_mapping'
	/home/hobbypunk/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/devise-4.7.1/lib/devise/rails/routes.rb:243:in `block in devise_for'
	/home/hobbypunk/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/devise-4.7.1/lib/devise/rails/routes.rb:242:in `each'
	/home/hobbypunk/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/devise-4.7.1/lib/devise/rails/routes.rb:242:in `devise_for'
	/home/hobbypunk/Entwicklung/Eigene_Projekte/DocumentManager/config/routes.rb:3:in `block in <main>'
```

**Comment by fxn** [comment]
I'll try to reproduce.

Meanwhile, if you use a literal string for `class_name`:

```ruby
class_name: "User::Identity"
```

the problem might disappear. I'd say literal strings in that option are more common, but your use of the class is legit and should work.

**Comment by hobbypunk90** [comment]
i know, it works as literal string 😁
but then the problem appears when i try to use the User::Identity in a method of the User, like this:
```
def self.from_omniauth(provider, uid, data, current_user = nil)
  identity = User::Identity.find_or_initialize_by provider: provider, uid: uid
  ...
end
```

**Comment by fxn** [comment]
I have created a minimal application that uses Devise and mimicks the structure above. All is loaded correctly.

I suspect there is something specific to your app that makes this happen.

Could you please write

```
Rails.autoloaders.log!
```

in _config/application.rb_ after the line that loads the 6.0 defaults, start the application, and share the whole trace including the exception backtrace?

**Comment by hobbypunk90** [comment]
sure, https://gist.github.com/hobbypunk90/0f1297c40f365d811a8988a664c036e9
i found an other strange behaviour:
the problem only exists in rubymine's debug mode, when i run it normaly in works

**Comment by fxn** [comment]
Ah! That’s it.

There is a limitation due to the way debuggers use Tracepoint that prevents Zeitwerk from loading child constants in explicit namespaces. It is not a bug technically.

Should probably document it.

I am on my phone, just a quick heads up.

**Comment by hobbypunk90** [comment]
yes, i found the issues with that problem a few minutes ago.
In RubyMine the workaround from https://youtrack.jetbrains.com/issue/RUBY-24781?_ga=2.36567712.1038145550.1568583449-407607673.1568216041 helps a lot.
switching from ruby-debug-ide version 0.8.0-betaX, which is installed by rubymine, to 0.7.0 helps to get it start again 🙂

**Comment by fxn** [comment]
So, this is no longer an issue in RubyMine with that version of the gem?

**Comment by fxn** [comment]
I like keeping issues and PRs to 0 in this project.

Since this is a fundamental limitation of Ruby and the way both gems are written, I believe the best course of action here is to document the incompatibility, and a workaround.

There is now [a section in the README](https://github.com/fxn/zeitwerk#autoloading-explicit-namespaces-and-debuggers) covering this. I worded it in kind of a generic way as a firts draft, though I am not 100% sure the debugger in RubyMine uses TracePoint. I'll tweak it if needed, but for now I think we can close.

Thanks!
