### ISSUE TITLE
Question Conflict File Path with gem

### ISSUE THREAD

**Issue by cobafan** [fxn/zeitwerk#87]
Hi, I have question Conflict File Path with gem.

In my Rails project, I want to load Model class.
But raise uninitialized constant error.

I want to know best practices for conflict File Path with gem

For example:

```
# MyRailsApp/app/models/foo.rb in my Rails project
require "MyRailsApp/vendor/bundle/ruby/2.5.0/bundler/gems/hoge-gem/app/models/foo.rb"
class Foo
end

# vendor/bundle/ruby/2.5.0/bundler/gems/hoge-gem/app/models/foo.rb

class Foo
end
```

```
$ rails c
[1] pry(main)> Foo
NameError: uninitialized constant Foo
Did you mean?  Foo
from (pry):1:in `<main>'
```

I append infomation If loss of infomation.

**Comment by fxn** [comment]
The `Foo` class is not owned by your project, apparently, but a gem defines it, and your app reopens the class/module.

So this particular class/module cannot be autoloaded/reloaded and Zeitwerk cannot handle it, it can only _reopen_ an existing class or module.

To see what you could do, could you please share the example with actual class/module name and give a bit more of context about it? It acts as namespace too? Tell us a bit more please.

**Comment by fxn** [comment]
Ah, is the gem an engine?

**Comment by cobafan** [comment]
Yes, This is engine.

**Comment by cobafan** [comment]
ex: 

``` vendor/bundle/ruby/2.5.0/bundler/gems/whose-gem/lib/whose-gem/engine.rb
module WhoseGem
  class Engine < ::Rails::Engine
    isolate_namespace WhoseGem
  end
end
```

``` vendor/bundle/ruby/2.5.0/bundler/gems/whose-gem/app/models/hoge.rb
class Hoge
end
```

``` app/models/hoge.rb
require "#{WhoseGem::Engine.root}/app/models/hoge.rb"
class Hoge

end

```

**Comment by fxn** [comment]
The autoload paths of the application take precendence over the autoload paths of engines. That means, Rails is going to consider your `foo.rb` first, and disregard the one in the engine as something autoloadable.

I believe the following would work:

```ruby
# app/models/hoge.rb
load "#{WhoseGem::Engine.root}/app/models/hoge.rb"
class Hoge
end
```

It is important to use `load`, because when `Hodge` is reloaded, you want to evaluate the file in the engine again.

Can you try please?

**Comment by cobafan** [comment]
I appreciate your advice.
I try to  `use load` tomorrow morning!

**Comment by cobafan** [comment]
I try to `use load`. but, not load. error is `uninitialized constant error`.
Is there likely another problem if not work load?

**Comment by fxn** [comment]
Probably. Can you reproduce in a minimal application?

**Comment by cobafan** [comment]
I try.

**Comment by cobafan** [comment]
I tried to reproduction, but i cannot.
maybe, exists other problem?

I keep doing reproduction. but you may probably clone this issue.
I appreciate your comment.

`mountable enfine gem` 
https://github.com/cobafan/sample_mountable_engine

`minimum-RailsApplication`
https://github.com/cobafan/min-app

**Comment by cobafan** [comment]
I apologize, I found other problem.

I took a misstake dupricated select autoload path.
I appriciate your comment. 

```
config.autoload_paths += %W(#{config.root}/app/models/)
config.autoload_paths += %W(#{config.root}/app/models/hoge)
```
