### ISSUE TITLE
Removing constant after initializers loading in Rails 6

### ISSUE THREAD

**Issue by woarewe** [fxn/zeitwerk#90]
Hello!
I have one question about zeitwerk work on the step when rails application is loading initializers.
So, my project has ```module Recaptcha```, its realization looks like that:
[project_root/lib/recaptcha.rb](https://github.com/woarewe/zeitwerk-initializers-behavior/blob/master/lib/recaptcha.rb)
```ruby
# frozen_string_literal: true

module Recaptcha
  @config = Config.instance

  class << self
    attr_reader :config

    def setup
      yield config if block_given?
    end
  end
end
```
[Config](https://github.com/woarewe/zeitwerk-initializers-behavior/blob/master/lib/recaptcha/config.rb) is a singleton class that has two accessors.
```ruby
# frozen_string_literal: true

module Recaptcha
  class Config
    include Singleton

    attr_accessor :site_key, :secret_key
  end
end
```

site_key and secret_key are two values that are stored in credentials.yml.enc, looks like that:
```yml
recaptcha:
        site_key: fake_site_key
        secret_key: fake_secret_key
```

So, to be sure, that required values are present in credentials and I can use it everywhere anytime, I put their fetching to [initializers/recaptcha.rb](https://github.com/woarewe/zeitwerk-initializers-behavior/blob/master/config/initializers/recaptcha.rb)
```ruby
# frozen_string_literal: true

recaptcha_credentials = Rails.application.credentials.fetch(:recaptcha)

Recaptcha.setup do |config|
  config.site_key = recaptcha_credentials.fetch(:site_key)
  config.secret_key = recaptcha_credentials.fetch(:secret_key)
end
```

And when I finished writing this code and started testing I got one interesting situation. When I'm running my rails console and trying to check ```Recaptcha.config``` value I get empty object without set values. I spent little time to inspect this situation and detected some notes:
1) When I stop ruby via binding.pry in initalizers code, and check ```Recaptcha.object_id``` I get one value, but after when the app is loaded in rails console I get another value.
2) I thought, that this problem because of spring, or bootsnap and some other rails caching, but if [I change](https://github.com/woarewe/zeitwerk-initializers-behavior/blob/master/config/application.rb#L28)  autoloader value to ```:classic``` in application.rb then all work fine.

@fxn, Please, could you help me and explain, why it works like that. I don't want to switch rails loader to classic mode because I hate const_missing way.

My repo with code:
https://github.com/woarewe/zeitwerk-initializers-behavior

 For your better and fast inspection, I pushed master.key, add pry-byebug to Gemfile and disabled spring and bootsnap, you can also inspect all changes in my two commits.
Thank you very much for your attention, and for the amazing ruby code loader.

**Comment by fxn** [comment]
Thanks for such a good issue description.

Note that does not work properly with `classic` either, look:

```
fxn@hilbert zeitwerk-initializers-behavior % bin/rails c
Loading development environment (Rails 6.0.0)
irb(main):001:0> Rails.application.config.autoloader
=> :classic
irb(main):002:0> Recaptcha.config
=> #<Recaptcha::Config:0x00007faee6d2d5b0 @site_key="fake_site_key", @secret_key="fake_secret_key">
irb(main):003:0> reload!
Reloading...
=> true
irb(main):004:0> Recaptcha.config
=> #<Recaptcha::Config:0x00007faee6e05668>
```

The fundamental problem is that reloading code does not reboot the application and the initializers do not run. So, on reloading, `Recaptcha` is a new module object, and the code that sets the keys does is not executed again, therefore they remain unset as the session above shows.

In your particular case, my advice would be to not add `lib` to `config.autoload_paths` and use a `require` in the initializer. Since `Recaptcha` is not autoloaded, it won't be erased and redefined on reloads and the configuration will be in place. As a compromise, then, if you change the implementation of that class, you'll need to reboot the app.

Some people have `app/lib` for `lib`-like stuff they want to autoload.

Does that help?

**Comment by woarewe** [comment]
Got it, thank you very much 👍 
I think I'll just add this part of ```lib``` to ignoring paths.
