### ISSUE TITLE
Tests issue with Ruby 2.5.3

### ISSUE THREAD

**Issue by pvalena** [fxn/zeitwerk#91]
```
Failure:
TestRequireInteraction#test_does_not_autovivify_while_loading_an_explicit_namespace__constant_is_not_yet_defined___file_first [/builddir/build/BUILD/zeitwerk-2.1.10/usr/share/gems/gems/zeitwerk-2.1.10/test/lib/zeitwerk/test_require_interaction.rb:165]
Minitest::Assertion: Expected /Hotel/ to match "undefined method `call' for nil:NilClass".

Failure:
TestRequireInteraction#test_does_not_autovivify_while_loading_an_explicit_namespace__constant_is_not_yet_defined___file_last [/builddir/build/BUILD/zeitwerk-2.1.10/usr/share/gems/gems/zeitwerk-2.1.10/test/lib/zeitwerk/test_require_interaction.rb:198]
Minitest::Assertion: Expected /Hotel/ to match "undefined method `call' for nil:NilClass".

163 tests, 379 assertions, 2 failures, 0 errors, 0 skips
error: Bad exit status from /var/tmp/rpm-tmp.ZhBcYt (%check)
    Bad exit status from /var/tmp/rpm-tmp.ZhBcYt (%check)
```
This does not occur with Ruby 2.6. I've encountered this when building for epel-8 in my COPR:

https://copr-be.cloud.fedoraproject.org/results/pvalena/rubygems/epel-8-x86_64/01060902-rubygem-zeitwerk/

(see build.log)

**Comment by fxn** [comment]
Strange. By now, I cannot reproduce:

```
~/prj/zeitwerk [tags/v2.1.10] % ruby -v
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin19]
~/prj/zeitwerk [tags/v2.1.10] % bin/test

# Running tests with run options --seed 63084:

.....................................................................................
..............................................................................


Finished tests in 2.118905s, 76.9265 tests/s, 178.8660 assertions/s.
```

Good news are the error in your build log, fortunately, does not seem to be realted to Zeitwerk itself. Apparently, for some reason [this stubbing](https://github.com/fxn/zeitwerk/blob/5772ba6eb0fb4ae1e27d8478ff249eb9e58dfda5/test/lib/zeitwerk/test_require_interaction.rb#L159) in the test suite is just not working as expected in your setup. The iterator is not getting a block, it seems. Does that ring a bell?

**Comment by fxn** [comment]
Does this happen if you run `bin/test` instead of the vanilla `ruby` call with a glob pattern?

**Comment by pvalena** [comment]
Maybe it's caused by us, as we're running the suite as follows:

```
+ ruby -Itest:lib -e 'Dir.glob "./test/**/test_*.rb", &method(:require)'
```

**Comment by fxn** [comment]
Let's see if we find out. In principle all files call `test_helper.rb`, so a priori that could work. But if `bin/test` does not reproduce the error, we have at least something that could help understand your build error.

**Comment by fxn** [comment]
Ah, one difference is that your build script is not using the `Gemfile`, that could be it. The purpose of `bin/test` is to encapsulate the way you run tests, which is trivial, but you type and need to memorize less. It accepts a file name if you want to run only one suite, and also the `focus` macro allows you to run one individual test only.

So, either `bin/test` or at least `bundle exec rake`.

**Comment by pvalena** [comment]
> So, either bin/test or at least bundle exec rake.

That's actually what we're trying to avoid, as at the 'package build' time we don't need bundler or rake. In the distribution there are installed `system-packaged-gems`, in one specific version and the build is done 'offline'. We also prefer to have more 'control' over what is done and tests run 'automatically' during this 'package build', or subsequent rebuilds, or test-rebuilds to ensure everything still works:
https://src.fedoraproject.org/rpms/rubygem-zeitwerk/blob/master/f/rubygem-zeitwerk.spec#_63

I'm sorry for confusion with Ruby 2.5.3, there may be other important differences:
  https://paste.fedoraproject.org/paste/CdC1PR94mLkej4EfV4nyww

Furthermore, on all stable and unstable Fedoras, everythings works, as outlined above. What fails are actually 'builds/tests' on EPEL-8 - builds on CentOS 8 base. _(In my COPR repo in this case, so not distributed, nor planned for ATM; so not all that important. I just wanted to let you know.)_

Knowing it's just a `stub` failure is fine.

Thank you for your time!

**Comment by fxn** [comment]
OK! However, it is still weird that it fails in that setup and not in others, and the suite is certainly not being executed in the correct way. Indeed, having a `Gemfile` whose dependencies are assumed in a project, and whose commands are expected to pass through Bundler is so common that I do not know if that way to run suites within the build process is going to work well in practice.

Only feedback though, you know better the rules/context of those builds and it is you call, of course.

This thread made me realize at least that there is no documentation about testing, and [just pushed some](https://github.com/fxn/zeitwerk#testing).

If you ever discover the reason behind that failure, please followup!
