### ISSUE TITLE
Reloading of overridden library code

### ISSUE THREAD

**Issue by paulfri** [fxn/zeitwerk#98]
Following up on this conversation: https://twitter.com/fxn/status/1190418390306963457

In a bundled gem, I have the following code (at `lib/override/me.rb`), which is required by `Bundler.require`:

```
module Override
  class Me
    def perform
      puts "I'm the original implementation!"
    end
  end
end
```

In the Rails app, I have the following code (at `app/models/override/me.rb`, or wherever in the load paths):

```
module Override
  class Me
    module NewImplementation
      def perform
        super
        puts "I'm the override!!!"
      end
    end

    prepend NewImplementation
  end
end
```

In a console, I get this output:

```
irb(main):001:0> Override::Me.new.perform
I'm the original implementation!
=> nil
irb(main):002:0> require_relative 'app/models/override/me'
=> true
irb(main):003:0> Override::Me.new.perform
I'm the original implementation!
I'm the override!!!
=> nil
```

In the first example, the Rails code is not autoloaded (because it's already loaded from the gem). After manually requiring the Rails code, the example works as expected.

My goal is to require the Rails code (ideally automatically but doesn't seem possible), but also to preserve reloading of the Rails code for development. Reloading of the gem code is not necessary. What's the best solution?

Thanks for all your great work on this library. 💚

Example repositories:
https://github.com/paulfri/override-me
https://github.com/paulfri/zeitwerk-override-example

**Comment by fxn** [comment]
There is a fundamental problem with this idea.

When you prepend the module, the module object is stored in the ancestor chain of the original class. If reloading was possible and was triggered, then you’d prepend _another_ module to that ancestor chain. The previous module object is still there. It is no longer reachable through the constant, but is cached there.

You’d see three strings printed when calling `perform`.

In a Rails app, you’d override in an initializer. You can have there the actual code depending on its size and personal taste. Alternatively, the overrides could be in `app/models` or some `overrides` folder. Then, you’d `require` them in an initializer, and tell `Rails.autoloaders.main` to ignore them (please check the API in the docs, I’m on my phone).

Sounds good?

**Comment by paulfri** [comment]
Thanks for the explanation! That should be suitable for our use case. I’ll give that a shot.
